package org.ims.dao.entity;
// Generated Nov 13, 2016 9:33:11 PM by Hibernate Tools 4.3.1



/**
 * ImsAppsettings generated by hbm2java
 */
public class ImsAppsettings  implements java.io.Serializable {


     private Integer id;
     private String appKey;
     private String appValue;

    public ImsAppsettings() {
    }

    public ImsAppsettings(String appKey, String appValue) {
       this.appKey = appKey;
       this.appValue = appValue;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getAppKey() {
        return this.appKey;
    }
    
    public void setAppKey(String appKey) {
        this.appKey = appKey;
    }
    public String getAppValue() {
        return this.appValue;
    }
    
    public void setAppValue(String appValue) {
        this.appValue = appValue;
    }




}


