package org.ims.dao.entity;
// Generated Nov 17, 2016 12:01:36 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * ImsBanktransactions generated by hbm2java
 */
public class ImsBanktransactions  implements java.io.Serializable {


     private Integer tranId;
     private ImsLogindetails imsLogindetails;
     private String accountNumber;
     private Date transactionDate;
     private BigDecimal transactionAmount;
     private String chequeNo;
     private Date chequeDate;
     private Character chequeStatus;
     private String chequeBank;
     private Character transactionStatus;
     private String remarks;
     private Integer tranFrom;
     private Integer tranType;
     private Date enteredDate;

    public ImsBanktransactions() {
    }

    public ImsBanktransactions(ImsLogindetails imsLogindetails, String accountNumber, Date transactionDate, BigDecimal transactionAmount, String chequeNo, Date chequeDate, Character chequeStatus, String chequeBank, Character transactionStatus, String remarks, Integer tranFrom, Integer tranType, Date enteredDate) {
       this.imsLogindetails = imsLogindetails;
       this.accountNumber = accountNumber;
       this.transactionDate = transactionDate;
       this.transactionAmount = transactionAmount;
       this.chequeNo = chequeNo;
       this.chequeDate = chequeDate;
       this.chequeStatus = chequeStatus;
       this.chequeBank = chequeBank;
       this.transactionStatus = transactionStatus;
       this.remarks = remarks;
       this.tranFrom = tranFrom;
       this.tranType = tranType;
       this.enteredDate = enteredDate;
    }
   
    public Integer getTranId() {
        return this.tranId;
    }
    
    public void setTranId(Integer tranId) {
        this.tranId = tranId;
    }
    public ImsLogindetails getImsLogindetails() {
        return this.imsLogindetails;
    }
    
    public void setImsLogindetails(ImsLogindetails imsLogindetails) {
        this.imsLogindetails = imsLogindetails;
    }
    public String getAccountNumber() {
        return this.accountNumber;
    }
    
    public void setAccountNumber(String accountNumber) {
        this.accountNumber = accountNumber;
    }
    public Date getTransactionDate() {
        return this.transactionDate;
    }
    
    public void setTransactionDate(Date transactionDate) {
        this.transactionDate = transactionDate;
    }
    public BigDecimal getTransactionAmount() {
        return this.transactionAmount;
    }
    
    public void setTransactionAmount(BigDecimal transactionAmount) {
        this.transactionAmount = transactionAmount;
    }
    public String getChequeNo() {
        return this.chequeNo;
    }
    
    public void setChequeNo(String chequeNo) {
        this.chequeNo = chequeNo;
    }
    public Date getChequeDate() {
        return this.chequeDate;
    }
    
    public void setChequeDate(Date chequeDate) {
        this.chequeDate = chequeDate;
    }
    public Character getChequeStatus() {
        return this.chequeStatus;
    }
    
    public void setChequeStatus(Character chequeStatus) {
        this.chequeStatus = chequeStatus;
    }
    public String getChequeBank() {
        return this.chequeBank;
    }
    
    public void setChequeBank(String chequeBank) {
        this.chequeBank = chequeBank;
    }
    public Character getTransactionStatus() {
        return this.transactionStatus;
    }
    
    public void setTransactionStatus(Character transactionStatus) {
        this.transactionStatus = transactionStatus;
    }
    public String getRemarks() {
        return this.remarks;
    }
    
    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }
    public Integer getTranFrom() {
        return this.tranFrom;
    }
    
    public void setTranFrom(Integer tranFrom) {
        this.tranFrom = tranFrom;
    }
    public Integer getTranType() {
        return this.tranType;
    }
    
    public void setTranType(Integer tranType) {
        this.tranType = tranType;
    }
    public Date getEnteredDate() {
        return this.enteredDate;
    }
    
    public void setEnteredDate(Date enteredDate) {
        this.enteredDate = enteredDate;
    }




}


