package org.ims.dao.entity;
// Generated 25 Jan, 2016 10:53:23 PM by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * ImsBankaccountdetails generated by hbm2java
 */
public class ImsBankaccountdetails  implements java.io.Serializable {


     private String accountNo;
     private String supplierOrdealerNo;
     private String bankName;
     private Character customerType;
     private Long enteredBy;
     private Date enteredDate;

    public ImsBankaccountdetails() {
    }

	
    public ImsBankaccountdetails(String accountNo) {
        this.accountNo = accountNo;
    }
    public ImsBankaccountdetails(String accountNo, String supplierOrdealerNo, String bankName, Character customerType, Long enteredBy, Date enteredDate) {
       this.accountNo = accountNo;
       this.supplierOrdealerNo = supplierOrdealerNo;
       this.bankName = bankName;
       this.customerType = customerType;
       this.enteredBy = enteredBy;
       this.enteredDate = enteredDate;
    }
   
    public String getAccountNo() {
        return this.accountNo;
    }
    
    public void setAccountNo(String accountNo) {
        this.accountNo = accountNo;
    }
    public String getSupplierOrdealerNo() {
        return this.supplierOrdealerNo;
    }
    
    public void setSupplierOrdealerNo(String supplierOrdealerNo) {
        this.supplierOrdealerNo = supplierOrdealerNo;
    }
    public String getBankName() {
        return this.bankName;
    }
    
    public void setBankName(String bankName) {
        this.bankName = bankName;
    }
    public Character getCustomerType() {
        return this.customerType;
    }
    
    public void setCustomerType(Character customerType) {
        this.customerType = customerType;
    }
    public Long getEnteredBy() {
        return this.enteredBy;
    }
    
    public void setEnteredBy(Long enteredBy) {
        this.enteredBy = enteredBy;
    }
    public Date getEnteredDate() {
        return this.enteredDate;
    }
    
    public void setEnteredDate(Date enteredDate) {
        this.enteredDate = enteredDate;
    }




}


