package org.ims.dao.entity;
// Generated 25 Jan, 2016 10:53:23 PM by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * ImsDealermaster generated by hbm2java
 */
public class ImsDealermaster  implements java.io.Serializable {


     private String dealerNumber;
     private ImsLogindetails imsLogindetails;
     private String companyName;
     private String companywebsite;
     private String companyEmail;
     private String comapanyAddress;
     private String tinNumber;
     private String cstnumber;
     private String pannumber;
     private byte[] vccertificate;
     private String offlicePhNumber;
     private Date enteredDate;
     private Boolean status;
     private Set imsDealersauthorizers = new HashSet(0);
     private Set imsOrderdetailses = new HashSet(0);
     private Set imsDealersauthorizers_1 = new HashSet(0);
     private Set imsOrderdetailses_1 = new HashSet(0);

    public ImsDealermaster() {
    }

	
    public ImsDealermaster(String dealerNumber, ImsLogindetails imsLogindetails, String companyName, String tinNumber, String cstnumber, Date enteredDate) {
        this.dealerNumber = dealerNumber;
        this.imsLogindetails = imsLogindetails;
        this.companyName = companyName;
        this.tinNumber = tinNumber;
        this.cstnumber = cstnumber;
        this.enteredDate = enteredDate;
    }
    public ImsDealermaster(String dealerNumber, ImsLogindetails imsLogindetails, String companyName, String companywebsite, String companyEmail, String comapanyAddress, String tinNumber, String cstnumber, String pannumber, byte[] vccertificate, String offlicePhNumber, Date enteredDate, Boolean status, Set imsDealersauthorizers, Set imsOrderdetailses, Set imsDealersauthorizers_1, Set imsOrderdetailses_1) {
       this.dealerNumber = dealerNumber;
       this.imsLogindetails = imsLogindetails;
       this.companyName = companyName;
       this.companywebsite = companywebsite;
       this.companyEmail = companyEmail;
       this.comapanyAddress = comapanyAddress;
       this.tinNumber = tinNumber;
       this.cstnumber = cstnumber;
       this.pannumber = pannumber;
       this.vccertificate = vccertificate;
       this.offlicePhNumber = offlicePhNumber;
       this.enteredDate = enteredDate;
       this.status = status;
       this.imsDealersauthorizers = imsDealersauthorizers;
       this.imsOrderdetailses = imsOrderdetailses;
       this.imsDealersauthorizers_1 = imsDealersauthorizers_1;
       this.imsOrderdetailses_1 = imsOrderdetailses_1;
    }
   
    public String getDealerNumber() {
        return this.dealerNumber;
    }
    
    public void setDealerNumber(String dealerNumber) {
        this.dealerNumber = dealerNumber;
    }
    public ImsLogindetails getImsLogindetails() {
        return this.imsLogindetails;
    }
    
    public void setImsLogindetails(ImsLogindetails imsLogindetails) {
        this.imsLogindetails = imsLogindetails;
    }
    public String getCompanyName() {
        return this.companyName;
    }
    
    public void setCompanyName(String companyName) {
        this.companyName = companyName;
    }
    public String getCompanywebsite() {
        return this.companywebsite;
    }
    
    public void setCompanywebsite(String companywebsite) {
        this.companywebsite = companywebsite;
    }
    public String getCompanyEmail() {
        return this.companyEmail;
    }
    
    public void setCompanyEmail(String companyEmail) {
        this.companyEmail = companyEmail;
    }
    public String getComapanyAddress() {
        return this.comapanyAddress;
    }
    
    public void setComapanyAddress(String comapanyAddress) {
        this.comapanyAddress = comapanyAddress;
    }
    public String getTinNumber() {
        return this.tinNumber;
    }
    
    public void setTinNumber(String tinNumber) {
        this.tinNumber = tinNumber;
    }
    public String getCstnumber() {
        return this.cstnumber;
    }
    
    public void setCstnumber(String cstnumber) {
        this.cstnumber = cstnumber;
    }
    public String getPannumber() {
        return this.pannumber;
    }
    
    public void setPannumber(String pannumber) {
        this.pannumber = pannumber;
    }
    public byte[] getVccertificate() {
        return this.vccertificate;
    }
    
    public void setVccertificate(byte[] vccertificate) {
        this.vccertificate = vccertificate;
    }
    public String getOfflicePhNumber() {
        return this.offlicePhNumber;
    }
    
    public void setOfflicePhNumber(String offlicePhNumber) {
        this.offlicePhNumber = offlicePhNumber;
    }
    public Date getEnteredDate() {
        return this.enteredDate;
    }
    
    public void setEnteredDate(Date enteredDate) {
        this.enteredDate = enteredDate;
    }
    public Boolean getStatus() {
        return this.status;
    }
    
    public void setStatus(Boolean status) {
        this.status = status;
    }
    public Set getImsDealersauthorizers() {
        return this.imsDealersauthorizers;
    }
    
    public void setImsDealersauthorizers(Set imsDealersauthorizers) {
        this.imsDealersauthorizers = imsDealersauthorizers;
    }
    public Set getImsOrderdetailses() {
        return this.imsOrderdetailses;
    }
    
    public void setImsOrderdetailses(Set imsOrderdetailses) {
        this.imsOrderdetailses = imsOrderdetailses;
    }
    public Set getImsDealersauthorizers_1() {
        return this.imsDealersauthorizers_1;
    }
    
    public void setImsDealersauthorizers_1(Set imsDealersauthorizers_1) {
        this.imsDealersauthorizers_1 = imsDealersauthorizers_1;
    }
    public Set getImsOrderdetailses_1() {
        return this.imsOrderdetailses_1;
    }
    
    public void setImsOrderdetailses_1(Set imsOrderdetailses_1) {
        this.imsOrderdetailses_1 = imsOrderdetailses_1;
    }

    @Override
    public String toString() {
        return "ImsDealermaster{" + "dealerNumber=" + dealerNumber + ", companyName=" + companyName + ", companywebsite=" + companywebsite + ", companyEmail=" + companyEmail + ", comapanyAddress=" + comapanyAddress + ", tinNumber=" + tinNumber + ", cstnumber=" + cstnumber + ", pannumber=" + pannumber + ", vccertificate=" + vccertificate + ", offlicePhNumber=" + offlicePhNumber + ", enteredDate=" + enteredDate + ", status=" + status + '}';
    }

   




}


