package org.ims.dao.entity;
// Generated Dec 27, 2016 11:33:32 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * ImsEmployee generated by hbm2java
 */
public class ImsEmployee  implements java.io.Serializable {


     private String employeeId;
     private ImsGenraldefinition imsGenraldefinitionByDesgnation;
     private ImsGenraldefinition imsGenraldefinitionByIdProof;
     private ImsGrouprights imsGrouprights;
     private String employeeName;
     private Date dob;
     private String address;
     private String phoneNo;
     private String emailId;
     private Date joinDate;
     private Boolean status;
     private long enteredBy;
     private Date enteredDate;
     private Set imsLogindetailses = new HashSet(0);

    public ImsEmployee() {
    }

	
    public ImsEmployee(String employeeId, ImsGenraldefinition imsGenraldefinitionByDesgnation, ImsGenraldefinition imsGenraldefinitionByIdProof, ImsGrouprights imsGrouprights, String employeeName, Date dob, String phoneNo, long enteredBy, Date enteredDate) {
        this.employeeId = employeeId;
        this.imsGenraldefinitionByDesgnation = imsGenraldefinitionByDesgnation;
        this.imsGenraldefinitionByIdProof = imsGenraldefinitionByIdProof;
        this.imsGrouprights = imsGrouprights;
        this.employeeName = employeeName;
        this.dob = dob;
        this.phoneNo = phoneNo;
        this.enteredBy = enteredBy;
        this.enteredDate = enteredDate;
    }
    public ImsEmployee(String employeeId, ImsGenraldefinition imsGenraldefinitionByDesgnation, ImsGenraldefinition imsGenraldefinitionByIdProof, ImsGrouprights imsGrouprights, String employeeName, Date dob, String address, String phoneNo, String emailId, Date joinDate, Boolean status, long enteredBy, Date enteredDate, Set imsLogindetailses) {
       this.employeeId = employeeId;
       this.imsGenraldefinitionByDesgnation = imsGenraldefinitionByDesgnation;
       this.imsGenraldefinitionByIdProof = imsGenraldefinitionByIdProof;
       this.imsGrouprights = imsGrouprights;
       this.employeeName = employeeName;
       this.dob = dob;
       this.address = address;
       this.phoneNo = phoneNo;
       this.emailId = emailId;
       this.joinDate = joinDate;
       this.status = status;
       this.enteredBy = enteredBy;
       this.enteredDate = enteredDate;
       this.imsLogindetailses = imsLogindetailses;
    }
   
    public String getEmployeeId() {
        return this.employeeId;
    }
    
    public void setEmployeeId(String employeeId) {
        this.employeeId = employeeId;
    }
    public ImsGenraldefinition getImsGenraldefinitionByDesgnation() {
        return this.imsGenraldefinitionByDesgnation;
    }
    
    public void setImsGenraldefinitionByDesgnation(ImsGenraldefinition imsGenraldefinitionByDesgnation) {
        this.imsGenraldefinitionByDesgnation = imsGenraldefinitionByDesgnation;
    }
    public ImsGenraldefinition getImsGenraldefinitionByIdProof() {
        return this.imsGenraldefinitionByIdProof;
    }
    
    public void setImsGenraldefinitionByIdProof(ImsGenraldefinition imsGenraldefinitionByIdProof) {
        this.imsGenraldefinitionByIdProof = imsGenraldefinitionByIdProof;
    }
    public ImsGrouprights getImsGrouprights() {
        return this.imsGrouprights;
    }
    
    public void setImsGrouprights(ImsGrouprights imsGrouprights) {
        this.imsGrouprights = imsGrouprights;
    }
    public String getEmployeeName() {
        return this.employeeName;
    }
    
    public void setEmployeeName(String employeeName) {
        this.employeeName = employeeName;
    }
    public Date getDob() {
        return this.dob;
    }
    
    public void setDob(Date dob) {
        this.dob = dob;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public String getPhoneNo() {
        return this.phoneNo;
    }
    
    public void setPhoneNo(String phoneNo) {
        this.phoneNo = phoneNo;
    }
    public String getEmailId() {
        return this.emailId;
    }
    
    public void setEmailId(String emailId) {
        this.emailId = emailId;
    }
    public Date getJoinDate() {
        return this.joinDate;
    }
    
    public void setJoinDate(Date joinDate) {
        this.joinDate = joinDate;
    }
    public Boolean getStatus() {
        return this.status;
    }
    
    public void setStatus(Boolean status) {
        this.status = status;
    }
    public long getEnteredBy() {
        return this.enteredBy;
    }
    
    public void setEnteredBy(long enteredBy) {
        this.enteredBy = enteredBy;
    }
    public Date getEnteredDate() {
        return this.enteredDate;
    }
    
    public void setEnteredDate(Date enteredDate) {
        this.enteredDate = enteredDate;
    }
    public Set getImsLogindetailses() {
        return this.imsLogindetailses;
    }
    
    public void setImsLogindetailses(Set imsLogindetailses) {
        this.imsLogindetailses = imsLogindetailses;
    }




}


