package org.ims.dao.entity;
// Generated 25 Jan, 2016 10:53:23 PM by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * ImsGenraldefinition generated by hbm2java
 */
public class ImsGenraldefinition  implements java.io.Serializable {


     private String gdCode;
     private ImsLogindetails imsLogindetails;
     private String gdAbb;
     private String gdName;
     private Date enteredDate;
     private Set imsEmployeesForDesgnation = new HashSet(0);
     private Set imsEmployeesForDesgnation_1 = new HashSet(0);
     private Set imsEmployeesForIdProof = new HashSet(0);
     private Set imsEmployeesForIdProof_1 = new HashSet(0);

    public ImsGenraldefinition() {
    }

	
    public ImsGenraldefinition(String gdCode, ImsLogindetails imsLogindetails, String gdName, Date enteredDate) {
        this.gdCode = gdCode;
        this.imsLogindetails = imsLogindetails;
        this.gdName = gdName;
        this.enteredDate = enteredDate;
    }
    public ImsGenraldefinition(String gdCode, ImsLogindetails imsLogindetails, String gdAbb, String gdName, Date enteredDate, Set imsEmployeesForDesgnation, Set imsEmployeesForDesgnation_1, Set imsEmployeesForIdProof, Set imsEmployeesForIdProof_1) {
       this.gdCode = gdCode;
       this.imsLogindetails = imsLogindetails;
       this.gdAbb = gdAbb;
       this.gdName = gdName;
       this.enteredDate = enteredDate;
       this.imsEmployeesForDesgnation = imsEmployeesForDesgnation;
       this.imsEmployeesForDesgnation_1 = imsEmployeesForDesgnation_1;
       this.imsEmployeesForIdProof = imsEmployeesForIdProof;
       this.imsEmployeesForIdProof_1 = imsEmployeesForIdProof_1;
    }
   
    public String getGdCode() {
        return this.gdCode;
    }
    
    public void setGdCode(String gdCode) {
        this.gdCode = gdCode;
    }
    public ImsLogindetails getImsLogindetails() {
        return this.imsLogindetails;
    }
    
    public void setImsLogindetails(ImsLogindetails imsLogindetails) {
        this.imsLogindetails = imsLogindetails;
    }
    public String getGdAbb() {
        return this.gdAbb;
    }
    
    public void setGdAbb(String gdAbb) {
        this.gdAbb = gdAbb;
    }
    public String getGdName() {
        return this.gdName;
    }
    
    public void setGdName(String gdName) {
        this.gdName = gdName;
    }
    public Date getEnteredDate() {
        return this.enteredDate;
    }
    
    public void setEnteredDate(Date enteredDate) {
        this.enteredDate = enteredDate;
    }
    public Set getImsEmployeesForDesgnation() {
        return this.imsEmployeesForDesgnation;
    }
    
    public void setImsEmployeesForDesgnation(Set imsEmployeesForDesgnation) {
        this.imsEmployeesForDesgnation = imsEmployeesForDesgnation;
    }
    public Set getImsEmployeesForDesgnation_1() {
        return this.imsEmployeesForDesgnation_1;
    }
    
    public void setImsEmployeesForDesgnation_1(Set imsEmployeesForDesgnation_1) {
        this.imsEmployeesForDesgnation_1 = imsEmployeesForDesgnation_1;
    }
    public Set getImsEmployeesForIdProof() {
        return this.imsEmployeesForIdProof;
    }
    
    public void setImsEmployeesForIdProof(Set imsEmployeesForIdProof) {
        this.imsEmployeesForIdProof = imsEmployeesForIdProof;
    }
    public Set getImsEmployeesForIdProof_1() {
        return this.imsEmployeesForIdProof_1;
    }
    
    public void setImsEmployeesForIdProof_1(Set imsEmployeesForIdProof_1) {
        this.imsEmployeesForIdProof_1 = imsEmployeesForIdProof_1;
    }




}


