package org.ims.dao.entity;
// Generated Dec 26, 2016 9:20:06 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * ImsGrouprights generated by hbm2java
 */
public class ImsGrouprights  implements java.io.Serializable {


     private long groupId;
     private ImsLogindetails imsLogindetails;
     private String groupName;
     private String groupRights;
     private Date enteredDate;
     private Set imsEmployees = new HashSet(0);

    public ImsGrouprights() {
    }

	
    public ImsGrouprights(long groupId, ImsLogindetails imsLogindetails, String groupName, String groupRights, Date enteredDate) {
        this.groupId = groupId;
        this.imsLogindetails = imsLogindetails;
        this.groupName = groupName;
        this.groupRights = groupRights;
        this.enteredDate = enteredDate;
    }
    public ImsGrouprights(long groupId, ImsLogindetails imsLogindetails, String groupName, String groupRights, Date enteredDate, Set imsEmployees) {
       this.groupId = groupId;
       this.imsLogindetails = imsLogindetails;
       this.groupName = groupName;
       this.groupRights = groupRights;
       this.enteredDate = enteredDate;
       this.imsEmployees = imsEmployees;
    }
   
    public long getGroupId() {
        return this.groupId;
    }
    
    public void setGroupId(long groupId) {
        this.groupId = groupId;
    }
    public ImsLogindetails getImsLogindetails() {
        return this.imsLogindetails;
    }
    
    public void setImsLogindetails(ImsLogindetails imsLogindetails) {
        this.imsLogindetails = imsLogindetails;
    }
    public String getGroupName() {
        return this.groupName;
    }
    
    public void setGroupName(String groupName) {
        this.groupName = groupName;
    }
    public String getGroupRights() {
        return this.groupRights;
    }
    
    public void setGroupRights(String groupRights) {
        this.groupRights = groupRights;
    }
    public Date getEnteredDate() {
        return this.enteredDate;
    }
    
    public void setEnteredDate(Date enteredDate) {
        this.enteredDate = enteredDate;
    }
    public Set getImsEmployees() {
        return this.imsEmployees;
    }
    
    public void setImsEmployees(Set imsEmployees) {
        this.imsEmployees = imsEmployees;
    }




}


