package org.ims.dao.entity;
// Generated Dec 27, 2016 11:33:32 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * ImsInvoiceMaster generated by hbm2java
 */
public class ImsInvoiceMaster  implements java.io.Serializable {


     private String invoiceNo;
     private ImsLogindetails imsLogindetails;
     private ImsManageorders imsManageorders;
     private Date invoiceDate;
     private Date paymentDueDate;
     private String repName;
     private String paymentTerms;
     private String frieghtTerms;
     private String deliveryTerm;
     private String transporter;
     private String transportMode;
     private String esugmaNo;
     private String destination;
     private String lrnoAndDate;
     private Date expectedDelivery;
     private String noOfPack;
     private String grossWieght;
     private BigDecimal fafcharges;
     private BigDecimal grossAmount;
     private BigDecimal excisePercentage;
     private BigDecimal exciseRate;
     private BigDecimal educationCessPercentage;
     private BigDecimal educationCessRate;
     private BigDecimal secEducCessPercentage;
     private BigDecimal secEducCessRate;
     private BigDecimal cstpercentage;
     private BigDecimal cstrate;
     private BigDecimal vattotal1;
     private BigDecimal vattotal2;
     private BigDecimal roundOff;
     private BigDecimal totalAmount;
     private BigDecimal balanceAmount;
     private Integer invoiceStatus;
     private Date enteredDate;
     private Set imsTransactiondetailses = new HashSet(0);

    public ImsInvoiceMaster() {
    }

	
    public ImsInvoiceMaster(String invoiceNo, ImsManageorders imsManageorders, Date invoiceDate) {
        this.invoiceNo = invoiceNo;
        this.imsManageorders = imsManageorders;
        this.invoiceDate = invoiceDate;
    }
    public ImsInvoiceMaster(String invoiceNo, ImsLogindetails imsLogindetails, ImsManageorders imsManageorders, Date invoiceDate, Date paymentDueDate, String repName, String paymentTerms, String frieghtTerms, String deliveryTerm, String transporter, String transportMode, String esugmaNo, String destination, String lrnoAndDate, Date expectedDelivery, String noOfPack, String grossWieght, BigDecimal fafcharges, BigDecimal grossAmount, BigDecimal excisePercentage, BigDecimal exciseRate, BigDecimal educationCessPercentage, BigDecimal educationCessRate, BigDecimal secEducCessPercentage, BigDecimal secEducCessRate, BigDecimal cstpercentage, BigDecimal cstrate, BigDecimal vattotal1, BigDecimal vattotal2, BigDecimal roundOff, BigDecimal totalAmount, BigDecimal balanceAmount, Integer invoiceStatus, Date enteredDate, Set imsTransactiondetailses) {
       this.invoiceNo = invoiceNo;
       this.imsLogindetails = imsLogindetails;
       this.imsManageorders = imsManageorders;
       this.invoiceDate = invoiceDate;
       this.paymentDueDate = paymentDueDate;
       this.repName = repName;
       this.paymentTerms = paymentTerms;
       this.frieghtTerms = frieghtTerms;
       this.deliveryTerm = deliveryTerm;
       this.transporter = transporter;
       this.transportMode = transportMode;
       this.esugmaNo = esugmaNo;
       this.destination = destination;
       this.lrnoAndDate = lrnoAndDate;
       this.expectedDelivery = expectedDelivery;
       this.noOfPack = noOfPack;
       this.grossWieght = grossWieght;
       this.fafcharges = fafcharges;
       this.grossAmount = grossAmount;
       this.excisePercentage = excisePercentage;
       this.exciseRate = exciseRate;
       this.educationCessPercentage = educationCessPercentage;
       this.educationCessRate = educationCessRate;
       this.secEducCessPercentage = secEducCessPercentage;
       this.secEducCessRate = secEducCessRate;
       this.cstpercentage = cstpercentage;
       this.cstrate = cstrate;
       this.vattotal1 = vattotal1;
       this.vattotal2 = vattotal2;
       this.roundOff = roundOff;
       this.totalAmount = totalAmount;
       this.balanceAmount = balanceAmount;
       this.invoiceStatus = invoiceStatus;
       this.enteredDate = enteredDate;
       this.imsTransactiondetailses = imsTransactiondetailses;
    }
   
    public String getInvoiceNo() {
        return this.invoiceNo;
    }
    
    public void setInvoiceNo(String invoiceNo) {
        this.invoiceNo = invoiceNo;
    }
    public ImsLogindetails getImsLogindetails() {
        return this.imsLogindetails;
    }
    
    public void setImsLogindetails(ImsLogindetails imsLogindetails) {
        this.imsLogindetails = imsLogindetails;
    }
    public ImsManageorders getImsManageorders() {
        return this.imsManageorders;
    }
    
    public void setImsManageorders(ImsManageorders imsManageorders) {
        this.imsManageorders = imsManageorders;
    }
    public Date getInvoiceDate() {
        return this.invoiceDate;
    }
    
    public void setInvoiceDate(Date invoiceDate) {
        this.invoiceDate = invoiceDate;
    }
    public Date getPaymentDueDate() {
        return this.paymentDueDate;
    }
    
    public void setPaymentDueDate(Date paymentDueDate) {
        this.paymentDueDate = paymentDueDate;
    }
    public String getRepName() {
        return this.repName;
    }
    
    public void setRepName(String repName) {
        this.repName = repName;
    }
    public String getPaymentTerms() {
        return this.paymentTerms;
    }
    
    public void setPaymentTerms(String paymentTerms) {
        this.paymentTerms = paymentTerms;
    }
    public String getFrieghtTerms() {
        return this.frieghtTerms;
    }
    
    public void setFrieghtTerms(String frieghtTerms) {
        this.frieghtTerms = frieghtTerms;
    }
    public String getDeliveryTerm() {
        return this.deliveryTerm;
    }
    
    public void setDeliveryTerm(String deliveryTerm) {
        this.deliveryTerm = deliveryTerm;
    }
    public String getTransporter() {
        return this.transporter;
    }
    
    public void setTransporter(String transporter) {
        this.transporter = transporter;
    }
    public String getTransportMode() {
        return this.transportMode;
    }
    
    public void setTransportMode(String transportMode) {
        this.transportMode = transportMode;
    }
    public String getEsugmaNo() {
        return this.esugmaNo;
    }
    
    public void setEsugmaNo(String esugmaNo) {
        this.esugmaNo = esugmaNo;
    }
    public String getDestination() {
        return this.destination;
    }
    
    public void setDestination(String destination) {
        this.destination = destination;
    }
    public String getLrnoAndDate() {
        return this.lrnoAndDate;
    }
    
    public void setLrnoAndDate(String lrnoAndDate) {
        this.lrnoAndDate = lrnoAndDate;
    }
    public Date getExpectedDelivery() {
        return this.expectedDelivery;
    }
    
    public void setExpectedDelivery(Date expectedDelivery) {
        this.expectedDelivery = expectedDelivery;
    }
    public String getNoOfPack() {
        return this.noOfPack;
    }
    
    public void setNoOfPack(String noOfPack) {
        this.noOfPack = noOfPack;
    }
    public String getGrossWieght() {
        return this.grossWieght;
    }
    
    public void setGrossWieght(String grossWieght) {
        this.grossWieght = grossWieght;
    }
    public BigDecimal getFafcharges() {
        return this.fafcharges;
    }
    
    public void setFafcharges(BigDecimal fafcharges) {
        this.fafcharges = fafcharges;
    }
    public BigDecimal getGrossAmount() {
        return this.grossAmount;
    }
    
    public void setGrossAmount(BigDecimal grossAmount) {
        this.grossAmount = grossAmount;
    }
    public BigDecimal getExcisePercentage() {
        return this.excisePercentage;
    }
    
    public void setExcisePercentage(BigDecimal excisePercentage) {
        this.excisePercentage = excisePercentage;
    }
    public BigDecimal getExciseRate() {
        return this.exciseRate;
    }
    
    public void setExciseRate(BigDecimal exciseRate) {
        this.exciseRate = exciseRate;
    }
    public BigDecimal getEducationCessPercentage() {
        return this.educationCessPercentage;
    }
    
    public void setEducationCessPercentage(BigDecimal educationCessPercentage) {
        this.educationCessPercentage = educationCessPercentage;
    }
    public BigDecimal getEducationCessRate() {
        return this.educationCessRate;
    }
    
    public void setEducationCessRate(BigDecimal educationCessRate) {
        this.educationCessRate = educationCessRate;
    }
    public BigDecimal getSecEducCessPercentage() {
        return this.secEducCessPercentage;
    }
    
    public void setSecEducCessPercentage(BigDecimal secEducCessPercentage) {
        this.secEducCessPercentage = secEducCessPercentage;
    }
    public BigDecimal getSecEducCessRate() {
        return this.secEducCessRate;
    }
    
    public void setSecEducCessRate(BigDecimal secEducCessRate) {
        this.secEducCessRate = secEducCessRate;
    }
    public BigDecimal getCstpercentage() {
        return this.cstpercentage;
    }
    
    public void setCstpercentage(BigDecimal cstpercentage) {
        this.cstpercentage = cstpercentage;
    }
    public BigDecimal getCstrate() {
        return this.cstrate;
    }
    
    public void setCstrate(BigDecimal cstrate) {
        this.cstrate = cstrate;
    }
    public BigDecimal getVattotal1() {
        return this.vattotal1;
    }
    
    public void setVattotal1(BigDecimal vattotal1) {
        this.vattotal1 = vattotal1;
    }
    public BigDecimal getVattotal2() {
        return this.vattotal2;
    }
    
    public void setVattotal2(BigDecimal vattotal2) {
        this.vattotal2 = vattotal2;
    }
    public BigDecimal getRoundOff() {
        return this.roundOff;
    }
    
    public void setRoundOff(BigDecimal roundOff) {
        this.roundOff = roundOff;
    }
    public BigDecimal getTotalAmount() {
        return this.totalAmount;
    }
    
    public void setTotalAmount(BigDecimal totalAmount) {
        this.totalAmount = totalAmount;
    }
    public BigDecimal getBalanceAmount() {
        return this.balanceAmount;
    }
    
    public void setBalanceAmount(BigDecimal balanceAmount) {
        this.balanceAmount = balanceAmount;
    }
    public Integer getInvoiceStatus() {
        return this.invoiceStatus;
    }
    
    public void setInvoiceStatus(Integer invoiceStatus) {
        this.invoiceStatus = invoiceStatus;
    }
    public Date getEnteredDate() {
        return this.enteredDate;
    }
    
    public void setEnteredDate(Date enteredDate) {
        this.enteredDate = enteredDate;
    }
    public Set getImsTransactiondetailses() {
        return this.imsTransactiondetailses;
    }
    
    public void setImsTransactiondetailses(Set imsTransactiondetailses) {
        this.imsTransactiondetailses = imsTransactiondetailses;
    }




}


