package org.ims.dao.entity;
// Generated 25 Jan, 2016 10:53:23 PM by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * ImsLogindetails generated by hbm2java
 */
public class ImsLogindetails  implements java.io.Serializable {


     private long userId;
     private ImsEmployee imsEmployee;
     private String userName;
     private String userPassword;
     private boolean loginStatus;
     private Date loginDate;
     private Long enteredBy;
     private Date enteredDate;
     private Set imsOptionrightses = new HashSet(0);
     private Set imsOptionrightses_1 = new HashSet(0);
     private Set imsGrouprightses = new HashSet(0);
     private Set imsBanktransactionses = new HashSet(0);
     private Set imsProductcategories = new HashSet(0);
     private Set imsOrderdetailses = new HashSet(0);
     private Set imsSuppliermasters = new HashSet(0);
     private Set imsPurchaseproductdetailses = new HashSet(0);
     private Set imsSuppliersauthorizers = new HashSet(0);
     private Set imsGrouprightses_1 = new HashSet(0);
     private Set imsTransactiondetailses = new HashSet(0);
     private Set imsPurchasemasters = new HashSet(0);
     private Set imsDealersauthorizers = new HashSet(0);
     private Set imsProductdetailses = new HashSet(0);
     private Set imsBanktransactionses_1 = new HashSet(0);
     private Set imsPartnerdetailses = new HashSet(0);
     private Set imsProductcategories_1 = new HashSet(0);
     private Set imsPartnerdetailses_1 = new HashSet(0);
     private Set imsStockdetailses = new HashSet(0);
     private Set imsTransactiondetailses_1 = new HashSet(0);
     private Set imsDealermasters = new HashSet(0);
     private Set imsPurchasemasters_1 = new HashSet(0);
     private Set imsPurchaseproductdetailses_1 = new HashSet(0);
     private Set imsSuppliersauthorizers_1 = new HashSet(0);
     private Set imsDealermasters_1 = new HashSet(0);
     private Set imsGenraldefinitions = new HashSet(0);
     private Set imsDealersauthorizers_1 = new HashSet(0);
     private Set imsSuppliermasters_1 = new HashSet(0);
     private Set imsOrderdetailses_1 = new HashSet(0);
     private Set imsGenraldefinitions_1 = new HashSet(0);

    public ImsLogindetails() {
    }

	
    public ImsLogindetails(long userId, String userName, String userPassword, boolean loginStatus) {
        this.userId = userId;
        this.userName = userName;
        this.userPassword = userPassword;
        this.loginStatus = loginStatus;
    }
    public ImsLogindetails(long userId, ImsEmployee imsEmployee, String userName, String userPassword, boolean loginStatus, Date loginDate, Long enteredBy, Date enteredDate, Set imsOptionrightses, Set imsOptionrightses_1, Set imsGrouprightses, Set imsBanktransactionses, Set imsProductcategories, Set imsOrderdetailses, Set imsSuppliermasters, Set imsPurchaseproductdetailses, Set imsSuppliersauthorizers, Set imsGrouprightses_1, Set imsTransactiondetailses, Set imsPurchasemasters, Set imsDealersauthorizers, Set imsProductdetailses, Set imsBanktransactionses_1, Set imsPartnerdetailses, Set imsProductcategories_1, Set imsPartnerdetailses_1, Set imsStockdetailses, Set imsTransactiondetailses_1, Set imsDealermasters, Set imsPurchasemasters_1, Set imsPurchaseproductdetailses_1, Set imsSuppliersauthorizers_1, Set imsDealermasters_1, Set imsGenraldefinitions, Set imsDealersauthorizers_1, Set imsSuppliermasters_1, Set imsOrderdetailses_1, Set imsGenraldefinitions_1) {
       this.userId = userId;
       this.imsEmployee = imsEmployee;
       this.userName = userName;
       this.userPassword = userPassword;
       this.loginStatus = loginStatus;
       this.loginDate = loginDate;
       this.enteredBy = enteredBy;
       this.enteredDate = enteredDate;
       this.imsOptionrightses = imsOptionrightses;
       this.imsOptionrightses_1 = imsOptionrightses_1;
       this.imsGrouprightses = imsGrouprightses;
       this.imsBanktransactionses = imsBanktransactionses;
       this.imsProductcategories = imsProductcategories;
       this.imsOrderdetailses = imsOrderdetailses;
       this.imsSuppliermasters = imsSuppliermasters;
       this.imsPurchaseproductdetailses = imsPurchaseproductdetailses;
       this.imsSuppliersauthorizers = imsSuppliersauthorizers;
       this.imsGrouprightses_1 = imsGrouprightses_1;
       this.imsTransactiondetailses = imsTransactiondetailses;
       this.imsPurchasemasters = imsPurchasemasters;
       this.imsDealersauthorizers = imsDealersauthorizers;
       this.imsProductdetailses = imsProductdetailses;
       this.imsBanktransactionses_1 = imsBanktransactionses_1;
       this.imsPartnerdetailses = imsPartnerdetailses;
       this.imsProductcategories_1 = imsProductcategories_1;
       this.imsPartnerdetailses_1 = imsPartnerdetailses_1;
       this.imsStockdetailses = imsStockdetailses;
       this.imsTransactiondetailses_1 = imsTransactiondetailses_1;
       this.imsDealermasters = imsDealermasters;
       this.imsPurchasemasters_1 = imsPurchasemasters_1;
       this.imsPurchaseproductdetailses_1 = imsPurchaseproductdetailses_1;
       this.imsSuppliersauthorizers_1 = imsSuppliersauthorizers_1;
       this.imsDealermasters_1 = imsDealermasters_1;
       this.imsGenraldefinitions = imsGenraldefinitions;
       this.imsDealersauthorizers_1 = imsDealersauthorizers_1;
       this.imsSuppliermasters_1 = imsSuppliermasters_1;
       this.imsOrderdetailses_1 = imsOrderdetailses_1;
       this.imsGenraldefinitions_1 = imsGenraldefinitions_1;
    }
   
    public long getUserId() {
        return this.userId;
    }
    
    public void setUserId(long userId) {
        this.userId = userId;
    }
    public ImsEmployee getImsEmployee() {
        return this.imsEmployee;
    }
    
    public void setImsEmployee(ImsEmployee imsEmployee) {
        this.imsEmployee = imsEmployee;
    }
    public String getUserName() {
        return this.userName;
    }
    
    public void setUserName(String userName) {
        this.userName = userName;
    }
    public String getUserPassword() {
        return this.userPassword;
    }
    
    public void setUserPassword(String userPassword) {
        this.userPassword = userPassword;
    }
    public boolean isLoginStatus() {
        return this.loginStatus;
    }
    
    public void setLoginStatus(boolean loginStatus) {
        this.loginStatus = loginStatus;
    }
    public Date getLoginDate() {
        return this.loginDate;
    }
    
    public void setLoginDate(Date loginDate) {
        this.loginDate = loginDate;
    }
    public Long getEnteredBy() {
        return this.enteredBy;
    }
    
    public void setEnteredBy(Long enteredBy) {
        this.enteredBy = enteredBy;
    }
    public Date getEnteredDate() {
        return this.enteredDate;
    }
    
    public void setEnteredDate(Date enteredDate) {
        this.enteredDate = enteredDate;
    }
    public Set getImsOptionrightses() {
        return this.imsOptionrightses;
    }
    
    public void setImsOptionrightses(Set imsOptionrightses) {
        this.imsOptionrightses = imsOptionrightses;
    }
    public Set getImsOptionrightses_1() {
        return this.imsOptionrightses_1;
    }
    
    public void setImsOptionrightses_1(Set imsOptionrightses_1) {
        this.imsOptionrightses_1 = imsOptionrightses_1;
    }
    public Set getImsGrouprightses() {
        return this.imsGrouprightses;
    }
    
    public void setImsGrouprightses(Set imsGrouprightses) {
        this.imsGrouprightses = imsGrouprightses;
    }
    public Set getImsBanktransactionses() {
        return this.imsBanktransactionses;
    }
    
    public void setImsBanktransactionses(Set imsBanktransactionses) {
        this.imsBanktransactionses = imsBanktransactionses;
    }
    public Set getImsProductcategories() {
        return this.imsProductcategories;
    }
    
    public void setImsProductcategories(Set imsProductcategories) {
        this.imsProductcategories = imsProductcategories;
    }
    public Set getImsOrderdetailses() {
        return this.imsOrderdetailses;
    }
    
    public void setImsOrderdetailses(Set imsOrderdetailses) {
        this.imsOrderdetailses = imsOrderdetailses;
    }
    public Set getImsSuppliermasters() {
        return this.imsSuppliermasters;
    }
    
    public void setImsSuppliermasters(Set imsSuppliermasters) {
        this.imsSuppliermasters = imsSuppliermasters;
    }
    public Set getImsPurchaseproductdetailses() {
        return this.imsPurchaseproductdetailses;
    }
    
    public void setImsPurchaseproductdetailses(Set imsPurchaseproductdetailses) {
        this.imsPurchaseproductdetailses = imsPurchaseproductdetailses;
    }
    public Set getImsSuppliersauthorizers() {
        return this.imsSuppliersauthorizers;
    }
    
    public void setImsSuppliersauthorizers(Set imsSuppliersauthorizers) {
        this.imsSuppliersauthorizers = imsSuppliersauthorizers;
    }
    public Set getImsGrouprightses_1() {
        return this.imsGrouprightses_1;
    }
    
    public void setImsGrouprightses_1(Set imsGrouprightses_1) {
        this.imsGrouprightses_1 = imsGrouprightses_1;
    }
    public Set getImsTransactiondetailses() {
        return this.imsTransactiondetailses;
    }
    
    public void setImsTransactiondetailses(Set imsTransactiondetailses) {
        this.imsTransactiondetailses = imsTransactiondetailses;
    }
    public Set getImsPurchasemasters() {
        return this.imsPurchasemasters;
    }
    
    public void setImsPurchasemasters(Set imsPurchasemasters) {
        this.imsPurchasemasters = imsPurchasemasters;
    }
    public Set getImsDealersauthorizers() {
        return this.imsDealersauthorizers;
    }
    
    public void setImsDealersauthorizers(Set imsDealersauthorizers) {
        this.imsDealersauthorizers = imsDealersauthorizers;
    }
    public Set getImsProductdetailses() {
        return this.imsProductdetailses;
    }
    
    public void setImsProductdetailses(Set imsProductdetailses) {
        this.imsProductdetailses = imsProductdetailses;
    }
    public Set getImsBanktransactionses_1() {
        return this.imsBanktransactionses_1;
    }
    
    public void setImsBanktransactionses_1(Set imsBanktransactionses_1) {
        this.imsBanktransactionses_1 = imsBanktransactionses_1;
    }
    public Set getImsPartnerdetailses() {
        return this.imsPartnerdetailses;
    }
    
    public void setImsPartnerdetailses(Set imsPartnerdetailses) {
        this.imsPartnerdetailses = imsPartnerdetailses;
    }
    public Set getImsProductcategories_1() {
        return this.imsProductcategories_1;
    }
    
    public void setImsProductcategories_1(Set imsProductcategories_1) {
        this.imsProductcategories_1 = imsProductcategories_1;
    }
    public Set getImsPartnerdetailses_1() {
        return this.imsPartnerdetailses_1;
    }
    
    public void setImsPartnerdetailses_1(Set imsPartnerdetailses_1) {
        this.imsPartnerdetailses_1 = imsPartnerdetailses_1;
    }
    public Set getImsStockdetailses() {
        return this.imsStockdetailses;
    }
    
    public void setImsStockdetailses(Set imsStockdetailses) {
        this.imsStockdetailses = imsStockdetailses;
    }
    public Set getImsTransactiondetailses_1() {
        return this.imsTransactiondetailses_1;
    }
    
    public void setImsTransactiondetailses_1(Set imsTransactiondetailses_1) {
        this.imsTransactiondetailses_1 = imsTransactiondetailses_1;
    }
    public Set getImsDealermasters() {
        return this.imsDealermasters;
    }
    
    public void setImsDealermasters(Set imsDealermasters) {
        this.imsDealermasters = imsDealermasters;
    }
    public Set getImsPurchasemasters_1() {
        return this.imsPurchasemasters_1;
    }
    
    public void setImsPurchasemasters_1(Set imsPurchasemasters_1) {
        this.imsPurchasemasters_1 = imsPurchasemasters_1;
    }
    public Set getImsPurchaseproductdetailses_1() {
        return this.imsPurchaseproductdetailses_1;
    }
    
    public void setImsPurchaseproductdetailses_1(Set imsPurchaseproductdetailses_1) {
        this.imsPurchaseproductdetailses_1 = imsPurchaseproductdetailses_1;
    }
    public Set getImsSuppliersauthorizers_1() {
        return this.imsSuppliersauthorizers_1;
    }
    
    public void setImsSuppliersauthorizers_1(Set imsSuppliersauthorizers_1) {
        this.imsSuppliersauthorizers_1 = imsSuppliersauthorizers_1;
    }
    public Set getImsDealermasters_1() {
        return this.imsDealermasters_1;
    }
    
    public void setImsDealermasters_1(Set imsDealermasters_1) {
        this.imsDealermasters_1 = imsDealermasters_1;
    }
    public Set getImsGenraldefinitions() {
        return this.imsGenraldefinitions;
    }
    
    public void setImsGenraldefinitions(Set imsGenraldefinitions) {
        this.imsGenraldefinitions = imsGenraldefinitions;
    }
    public Set getImsDealersauthorizers_1() {
        return this.imsDealersauthorizers_1;
    }
    
    public void setImsDealersauthorizers_1(Set imsDealersauthorizers_1) {
        this.imsDealersauthorizers_1 = imsDealersauthorizers_1;
    }
    public Set getImsSuppliermasters_1() {
        return this.imsSuppliermasters_1;
    }
    
    public void setImsSuppliermasters_1(Set imsSuppliermasters_1) {
        this.imsSuppliermasters_1 = imsSuppliermasters_1;
    }
    public Set getImsOrderdetailses_1() {
        return this.imsOrderdetailses_1;
    }
    
    public void setImsOrderdetailses_1(Set imsOrderdetailses_1) {
        this.imsOrderdetailses_1 = imsOrderdetailses_1;
    }
    public Set getImsGenraldefinitions_1() {
        return this.imsGenraldefinitions_1;
    }
    
    public void setImsGenraldefinitions_1(Set imsGenraldefinitions_1) {
        this.imsGenraldefinitions_1 = imsGenraldefinitions_1;
    }




}


