package org.ims.dao.entity;
// Generated Dec 26, 2016 9:20:06 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * ImsLogindetails generated by hbm2java
 */
public class ImsLogindetails  implements java.io.Serializable {


     private long userId;
     private ImsEmployee imsEmployee;
     private String userName;
     private String userPassword;
     private boolean loginStatus;
     private Date loginDate;
     private Long enteredBy;
     private Date enteredDate;
     private Set imsPurchaseproductdetailses = new HashSet(0);
     private Set imsSuppliermasters = new HashSet(0);
     private Set imsTransactiondetailses = new HashSet(0);
     private Set imsInvoiceMasters = new HashSet(0);
     private Set imsBanktransactionses = new HashSet(0);
     private Set imsDealermasters = new HashSet(0);
     private Set imsStockdetailses = new HashSet(0);
     private Set imsGrouprightses = new HashSet(0);
     private Set imsSuppliersauthorizers = new HashSet(0);
     private Set imsOrderdetailses = new HashSet(0);
     private Set imsDealersauthorizers = new HashSet(0);
     private Set imsManageorderdetailses = new HashSet(0);
     private Set imsProductdetailses = new HashSet(0);
     private Set imsManageorderses = new HashSet(0);
     private Set imsPartnerdetailses = new HashSet(0);
     private Set imsGenraldefinitions = new HashSet(0);
     private Set imsOptionrightses = new HashSet(0);
     private Set imsProductcategories = new HashSet(0);
     private Set imsPurchasemasters = new HashSet(0);

    public ImsLogindetails() {
    }

	
    public ImsLogindetails(long userId, String userName, String userPassword, boolean loginStatus) {
        this.userId = userId;
        this.userName = userName;
        this.userPassword = userPassword;
        this.loginStatus = loginStatus;
    }
    public ImsLogindetails(long userId, ImsEmployee imsEmployee, String userName, String userPassword, boolean loginStatus, Date loginDate, Long enteredBy, Date enteredDate, Set imsPurchaseproductdetailses, Set imsSuppliermasters, Set imsTransactiondetailses, Set imsInvoiceMasters, Set imsBanktransactionses, Set imsDealermasters, Set imsStockdetailses, Set imsGrouprightses, Set imsSuppliersauthorizers, Set imsOrderdetailses, Set imsDealersauthorizers, Set imsManageorderdetailses, Set imsProductdetailses, Set imsManageorderses, Set imsPartnerdetailses, Set imsGenraldefinitions, Set imsOptionrightses, Set imsProductcategories, Set imsPurchasemasters) {
       this.userId = userId;
       this.imsEmployee = imsEmployee;
       this.userName = userName;
       this.userPassword = userPassword;
       this.loginStatus = loginStatus;
       this.loginDate = loginDate;
       this.enteredBy = enteredBy;
       this.enteredDate = enteredDate;
       this.imsPurchaseproductdetailses = imsPurchaseproductdetailses;
       this.imsSuppliermasters = imsSuppliermasters;
       this.imsTransactiondetailses = imsTransactiondetailses;
       this.imsInvoiceMasters = imsInvoiceMasters;
       this.imsBanktransactionses = imsBanktransactionses;
       this.imsDealermasters = imsDealermasters;
       this.imsStockdetailses = imsStockdetailses;
       this.imsGrouprightses = imsGrouprightses;
       this.imsSuppliersauthorizers = imsSuppliersauthorizers;
       this.imsOrderdetailses = imsOrderdetailses;
       this.imsDealersauthorizers = imsDealersauthorizers;
       this.imsManageorderdetailses = imsManageorderdetailses;
       this.imsProductdetailses = imsProductdetailses;
       this.imsManageorderses = imsManageorderses;
       this.imsPartnerdetailses = imsPartnerdetailses;
       this.imsGenraldefinitions = imsGenraldefinitions;
       this.imsOptionrightses = imsOptionrightses;
       this.imsProductcategories = imsProductcategories;
       this.imsPurchasemasters = imsPurchasemasters;
    }
   
    public long getUserId() {
        return this.userId;
    }
    
    public void setUserId(long userId) {
        this.userId = userId;
    }
    public ImsEmployee getImsEmployee() {
        return this.imsEmployee;
    }
    
    public void setImsEmployee(ImsEmployee imsEmployee) {
        this.imsEmployee = imsEmployee;
    }
    public String getUserName() {
        return this.userName;
    }
    
    public void setUserName(String userName) {
        this.userName = userName;
    }
    public String getUserPassword() {
        return this.userPassword;
    }
    
    public void setUserPassword(String userPassword) {
        this.userPassword = userPassword;
    }
    public boolean isLoginStatus() {
        return this.loginStatus;
    }
    
    public void setLoginStatus(boolean loginStatus) {
        this.loginStatus = loginStatus;
    }
    public Date getLoginDate() {
        return this.loginDate;
    }
    
    public void setLoginDate(Date loginDate) {
        this.loginDate = loginDate;
    }
    public Long getEnteredBy() {
        return this.enteredBy;
    }
    
    public void setEnteredBy(Long enteredBy) {
        this.enteredBy = enteredBy;
    }
    public Date getEnteredDate() {
        return this.enteredDate;
    }
    
    public void setEnteredDate(Date enteredDate) {
        this.enteredDate = enteredDate;
    }
    public Set getImsPurchaseproductdetailses() {
        return this.imsPurchaseproductdetailses;
    }
    
    public void setImsPurchaseproductdetailses(Set imsPurchaseproductdetailses) {
        this.imsPurchaseproductdetailses = imsPurchaseproductdetailses;
    }
    public Set getImsSuppliermasters() {
        return this.imsSuppliermasters;
    }
    
    public void setImsSuppliermasters(Set imsSuppliermasters) {
        this.imsSuppliermasters = imsSuppliermasters;
    }
    public Set getImsTransactiondetailses() {
        return this.imsTransactiondetailses;
    }
    
    public void setImsTransactiondetailses(Set imsTransactiondetailses) {
        this.imsTransactiondetailses = imsTransactiondetailses;
    }
    public Set getImsInvoiceMasters() {
        return this.imsInvoiceMasters;
    }
    
    public void setImsInvoiceMasters(Set imsInvoiceMasters) {
        this.imsInvoiceMasters = imsInvoiceMasters;
    }
    public Set getImsBanktransactionses() {
        return this.imsBanktransactionses;
    }
    
    public void setImsBanktransactionses(Set imsBanktransactionses) {
        this.imsBanktransactionses = imsBanktransactionses;
    }
    public Set getImsDealermasters() {
        return this.imsDealermasters;
    }
    
    public void setImsDealermasters(Set imsDealermasters) {
        this.imsDealermasters = imsDealermasters;
    }
    public Set getImsStockdetailses() {
        return this.imsStockdetailses;
    }
    
    public void setImsStockdetailses(Set imsStockdetailses) {
        this.imsStockdetailses = imsStockdetailses;
    }
    public Set getImsGrouprightses() {
        return this.imsGrouprightses;
    }
    
    public void setImsGrouprightses(Set imsGrouprightses) {
        this.imsGrouprightses = imsGrouprightses;
    }
    public Set getImsSuppliersauthorizers() {
        return this.imsSuppliersauthorizers;
    }
    
    public void setImsSuppliersauthorizers(Set imsSuppliersauthorizers) {
        this.imsSuppliersauthorizers = imsSuppliersauthorizers;
    }
    public Set getImsOrderdetailses() {
        return this.imsOrderdetailses;
    }
    
    public void setImsOrderdetailses(Set imsOrderdetailses) {
        this.imsOrderdetailses = imsOrderdetailses;
    }
    public Set getImsDealersauthorizers() {
        return this.imsDealersauthorizers;
    }
    
    public void setImsDealersauthorizers(Set imsDealersauthorizers) {
        this.imsDealersauthorizers = imsDealersauthorizers;
    }
    public Set getImsManageorderdetailses() {
        return this.imsManageorderdetailses;
    }
    
    public void setImsManageorderdetailses(Set imsManageorderdetailses) {
        this.imsManageorderdetailses = imsManageorderdetailses;
    }
    public Set getImsProductdetailses() {
        return this.imsProductdetailses;
    }
    
    public void setImsProductdetailses(Set imsProductdetailses) {
        this.imsProductdetailses = imsProductdetailses;
    }
    public Set getImsManageorderses() {
        return this.imsManageorderses;
    }
    
    public void setImsManageorderses(Set imsManageorderses) {
        this.imsManageorderses = imsManageorderses;
    }
    public Set getImsPartnerdetailses() {
        return this.imsPartnerdetailses;
    }
    
    public void setImsPartnerdetailses(Set imsPartnerdetailses) {
        this.imsPartnerdetailses = imsPartnerdetailses;
    }
    public Set getImsGenraldefinitions() {
        return this.imsGenraldefinitions;
    }
    
    public void setImsGenraldefinitions(Set imsGenraldefinitions) {
        this.imsGenraldefinitions = imsGenraldefinitions;
    }
    public Set getImsOptionrightses() {
        return this.imsOptionrightses;
    }
    
    public void setImsOptionrightses(Set imsOptionrightses) {
        this.imsOptionrightses = imsOptionrightses;
    }
    public Set getImsProductcategories() {
        return this.imsProductcategories;
    }
    
    public void setImsProductcategories(Set imsProductcategories) {
        this.imsProductcategories = imsProductcategories;
    }
    public Set getImsPurchasemasters() {
        return this.imsPurchasemasters;
    }
    
    public void setImsPurchasemasters(Set imsPurchasemasters) {
        this.imsPurchasemasters = imsPurchasemasters;
    }




}


