package org.ims.dao.entity;
// Generated Nov 13, 2016 9:33:11 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * ImsManageorderdetails generated by hbm2java
 */
public class ImsManageorderdetails  implements java.io.Serializable {


     private Integer id;
     private ImsLogindetails imsLogindetails;
     private ImsManageorders imsManageorders;
     private ImsProductdetails imsProductdetails;
     private Long orderQuantity;
     private Long dispatchedQuantity;
     private Double basicRate;
     private Double discount;
     private String particulars;
     private Double vat;
     private Double amount;
     private Date enteredDate;
     private Date lasModifiedDate;
     private Long modifedBy;

    public ImsManageorderdetails() {
    }

	
    public ImsManageorderdetails(ImsLogindetails imsLogindetails, Date enteredDate) {
        this.imsLogindetails = imsLogindetails;
        this.enteredDate = enteredDate;
    }
    public ImsManageorderdetails(ImsLogindetails imsLogindetails, ImsManageorders imsManageorders, ImsProductdetails imsProductdetails, Long orderQuantity, Long dispatchedQuantity, Double basicRate, Double discount, String particulars, Double vat, Double amount, Date enteredDate, Date lasModifiedDate, Long modifedBy) {
       this.imsLogindetails = imsLogindetails;
       this.imsManageorders = imsManageorders;
       this.imsProductdetails = imsProductdetails;
       this.orderQuantity = orderQuantity;
       this.dispatchedQuantity = dispatchedQuantity;
       this.basicRate = basicRate;
       this.discount = discount;
       this.particulars = particulars;
       this.vat = vat;
       this.amount = amount;
       this.enteredDate = enteredDate;
       this.lasModifiedDate = lasModifiedDate;
       this.modifedBy = modifedBy;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public ImsLogindetails getImsLogindetails() {
        return this.imsLogindetails;
    }
    
    public void setImsLogindetails(ImsLogindetails imsLogindetails) {
        this.imsLogindetails = imsLogindetails;
    }
    public ImsManageorders getImsManageorders() {
        return this.imsManageorders;
    }
    
    public void setImsManageorders(ImsManageorders imsManageorders) {
        this.imsManageorders = imsManageorders;
    }
    public ImsProductdetails getImsProductdetails() {
        return this.imsProductdetails;
    }
    
    public void setImsProductdetails(ImsProductdetails imsProductdetails) {
        this.imsProductdetails = imsProductdetails;
    }
    public Long getOrderQuantity() {
        return this.orderQuantity;
    }
    
    public void setOrderQuantity(Long orderQuantity) {
        this.orderQuantity = orderQuantity;
    }
    public Long getDispatchedQuantity() {
        return this.dispatchedQuantity;
    }
    
    public void setDispatchedQuantity(Long dispatchedQuantity) {
        this.dispatchedQuantity = dispatchedQuantity;
    }
    public Double getBasicRate() {
        return this.basicRate;
    }
    
    public void setBasicRate(Double basicRate) {
        this.basicRate = basicRate;
    }
    public Double getDiscount() {
        return this.discount;
    }
    
    public void setDiscount(Double discount) {
        this.discount = discount;
    }
    public String getParticulars() {
        return this.particulars;
    }
    
    public void setParticulars(String particulars) {
        this.particulars = particulars;
    }
    public Double getVat() {
        return this.vat;
    }
    
    public void setVat(Double vat) {
        this.vat = vat;
    }
    public Double getAmount() {
        return this.amount;
    }
    
    public void setAmount(Double amount) {
        this.amount = amount;
    }
    public Date getEnteredDate() {
        return this.enteredDate;
    }
    
    public void setEnteredDate(Date enteredDate) {
        this.enteredDate = enteredDate;
    }
    public Date getLasModifiedDate() {
        return this.lasModifiedDate;
    }
    
    public void setLasModifiedDate(Date lasModifiedDate) {
        this.lasModifiedDate = lasModifiedDate;
    }
    public Long getModifedBy() {
        return this.modifedBy;
    }
    
    public void setModifedBy(Long modifedBy) {
        this.modifedBy = modifedBy;
    }




}


