package org.ims.dao.entity;
// Generated Dec 27, 2016 11:33:32 PM by Hibernate Tools 4.3.1



/**
 * ImsOrderdetailsId generated by hbm2java
 */
public class ImsOrderdetailsId  implements java.io.Serializable {


     private int orderNo;
     private String productCode;

    public ImsOrderdetailsId() {
    }

    public ImsOrderdetailsId(int orderNo, String productCode) {
       this.orderNo = orderNo;
       this.productCode = productCode;
    }
   
    public int getOrderNo() {
        return this.orderNo;
    }
    
    public void setOrderNo(int orderNo) {
        this.orderNo = orderNo;
    }
    public String getProductCode() {
        return this.productCode;
    }
    
    public void setProductCode(String productCode) {
        this.productCode = productCode;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ImsOrderdetailsId) ) return false;
		 ImsOrderdetailsId castOther = ( ImsOrderdetailsId ) other; 
         
		 return (this.getOrderNo()==castOther.getOrderNo())
 && ( (this.getProductCode()==castOther.getProductCode()) || ( this.getProductCode()!=null && castOther.getProductCode()!=null && this.getProductCode().equals(castOther.getProductCode()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getOrderNo();
         result = 37 * result + ( getProductCode() == null ? 0 : this.getProductCode().hashCode() );
         return result;
   }   


}


