package org.ims.dao.entity;
// Generated Nov 13, 2016 9:33:11 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * ImsOptionrights generated by hbm2java
 */
public class ImsOptionrights  implements java.io.Serializable {


     private long moduleNumber;
     private ImsLogindetails imsLogindetails;
     private String moduleName;
     private Date createdDate;
     private Date updatedDate;

    public ImsOptionrights() {
    }

	
    public ImsOptionrights(long moduleNumber, ImsLogindetails imsLogindetails, String moduleName) {
        this.moduleNumber = moduleNumber;
        this.imsLogindetails = imsLogindetails;
        this.moduleName = moduleName;
    }
    public ImsOptionrights(long moduleNumber, ImsLogindetails imsLogindetails, String moduleName, Date createdDate, Date updatedDate) {
       this.moduleNumber = moduleNumber;
       this.imsLogindetails = imsLogindetails;
       this.moduleName = moduleName;
       this.createdDate = createdDate;
       this.updatedDate = updatedDate;
    }
   
    public long getModuleNumber() {
        return this.moduleNumber;
    }
    
    public void setModuleNumber(long moduleNumber) {
        this.moduleNumber = moduleNumber;
    }
    public ImsLogindetails getImsLogindetails() {
        return this.imsLogindetails;
    }
    
    public void setImsLogindetails(ImsLogindetails imsLogindetails) {
        this.imsLogindetails = imsLogindetails;
    }
    public String getModuleName() {
        return this.moduleName;
    }
    
    public void setModuleName(String moduleName) {
        this.moduleName = moduleName;
    }
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }
    public Date getUpdatedDate() {
        return this.updatedDate;
    }
    
    public void setUpdatedDate(Date updatedDate) {
        this.updatedDate = updatedDate;
    }




}


