package org.ims.dao.entity;
// Generated Nov 13, 2016 9:33:11 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * ImsOrderdetails generated by hbm2java
 */
public class ImsOrderdetails  implements java.io.Serializable {


     private ImsOrderdetailsId id;
     private ImsDealermaster imsDealermaster;
     private ImsLogindetails imsLogindetails;
     private ImsProductdetails imsProductdetails;
     private Date orderDateAndTime;
     private Integer quantity;
     private Integer dispatchedQty;
     private Integer balanceQty;
     private Double discount;
     private Double vat;
     private BigDecimal amount;
     private String remarks;
     private String status;
     private Date enteredDate;

    public ImsOrderdetails() {
    }

	
    public ImsOrderdetails(ImsOrderdetailsId id, ImsProductdetails imsProductdetails) {
        this.id = id;
        this.imsProductdetails = imsProductdetails;
    }
    public ImsOrderdetails(ImsOrderdetailsId id, ImsDealermaster imsDealermaster, ImsLogindetails imsLogindetails, ImsProductdetails imsProductdetails, Date orderDateAndTime, Integer quantity, Integer dispatchedQty, Integer balanceQty, Double discount, Double vat, BigDecimal amount, String remarks, String status, Date enteredDate) {
       this.id = id;
       this.imsDealermaster = imsDealermaster;
       this.imsLogindetails = imsLogindetails;
       this.imsProductdetails = imsProductdetails;
       this.orderDateAndTime = orderDateAndTime;
       this.quantity = quantity;
       this.dispatchedQty = dispatchedQty;
       this.balanceQty = balanceQty;
       this.discount = discount;
       this.vat = vat;
       this.amount = amount;
       this.remarks = remarks;
       this.status = status;
       this.enteredDate = enteredDate;
    }
   
    public ImsOrderdetailsId getId() {
        return this.id;
    }
    
    public void setId(ImsOrderdetailsId id) {
        this.id = id;
    }
    public ImsDealermaster getImsDealermaster() {
        return this.imsDealermaster;
    }
    
    public void setImsDealermaster(ImsDealermaster imsDealermaster) {
        this.imsDealermaster = imsDealermaster;
    }
    public ImsLogindetails getImsLogindetails() {
        return this.imsLogindetails;
    }
    
    public void setImsLogindetails(ImsLogindetails imsLogindetails) {
        this.imsLogindetails = imsLogindetails;
    }
    public ImsProductdetails getImsProductdetails() {
        return this.imsProductdetails;
    }
    
    public void setImsProductdetails(ImsProductdetails imsProductdetails) {
        this.imsProductdetails = imsProductdetails;
    }
    public Date getOrderDateAndTime() {
        return this.orderDateAndTime;
    }
    
    public void setOrderDateAndTime(Date orderDateAndTime) {
        this.orderDateAndTime = orderDateAndTime;
    }
    public Integer getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }
    public Integer getDispatchedQty() {
        return this.dispatchedQty;
    }
    
    public void setDispatchedQty(Integer dispatchedQty) {
        this.dispatchedQty = dispatchedQty;
    }
    public Integer getBalanceQty() {
        return this.balanceQty;
    }
    
    public void setBalanceQty(Integer balanceQty) {
        this.balanceQty = balanceQty;
    }
    public Double getDiscount() {
        return this.discount;
    }
    
    public void setDiscount(Double discount) {
        this.discount = discount;
    }
    public Double getVat() {
        return this.vat;
    }
    
    public void setVat(Double vat) {
        this.vat = vat;
    }
    public BigDecimal getAmount() {
        return this.amount;
    }
    
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }
    public String getRemarks() {
        return this.remarks;
    }
    
    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public Date getEnteredDate() {
        return this.enteredDate;
    }
    
    public void setEnteredDate(Date enteredDate) {
        this.enteredDate = enteredDate;
    }




}


