package org.ims.dao.entity;
// Generated 25 Jan, 2016 10:53:23 PM by Hibernate Tools 3.6.0


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * ImsPurchasemaster generated by hbm2java
 */
public class ImsPurchasemaster  implements java.io.Serializable {


     private String pinvoiceId;
     private ImsSuppliermaster imsSuppliermaster;
     private ImsLogindetails imsLogindetails;
     private String cashorCredit;
     private String supplierOrderNo;
     private String repName;
     private Date supplierInvoiceDate;
     private Date paymentDueDate;
     private String paymentTerms;
     private String frieghtTerm;
     private String deliverlyTerm;
     private String transporter;
     private String transportMode;
     private String esugamaNo;
     private String destination;
     private String lrnoandDate;
     private Date expectedDelivary;
     private Long noPacks;
     private BigDecimal grossWeight;
     private Long totalNoproducts;
     private BigDecimal vatfaf;
     private BigDecimal vatfafrate;
     private BigDecimal grossTotal;
     private BigDecimal excessPercentage;
     private BigDecimal excessRate;
     private BigDecimal educationCessPercentage;
     private BigDecimal educationCessRate;
     private BigDecimal secondaryEducationCessPercentage;
     private BigDecimal secondaryEducationCessRate;
     private BigDecimal cstpercentage;
     private BigDecimal cstrate;
     private BigDecimal vattotal1;
     private BigDecimal vattotal2;
     private BigDecimal roundOff;
     private BigDecimal totalAmount;
     private Date enteredDate;
     private Set imsPurchaseproductdetailses = new HashSet(0);
     private Set imsPurchaseproductdetailses_1 = new HashSet(0);

    public ImsPurchasemaster() {
    }

	
    public ImsPurchasemaster(String pinvoiceId, ImsSuppliermaster imsSuppliermaster, String cashorCredit) {
        this.pinvoiceId = pinvoiceId;
        this.imsSuppliermaster = imsSuppliermaster;
        this.cashorCredit = cashorCredit;
    }
    public ImsPurchasemaster(String pinvoiceId, ImsSuppliermaster imsSuppliermaster, ImsLogindetails imsLogindetails, String cashorCredit, String supplierOrderNo, String repName, Date supplierInvoiceDate, Date paymentDueDate, String paymentTerms, String frieghtTerm, String deliverlyTerm, String transporter, String transportMode, String esugamaNo, String destination, String lrnoandDate, Date expectedDelivary, Long noPacks, BigDecimal grossWeight, Long totalNoproducts, BigDecimal vatfaf, BigDecimal vatfafrate, BigDecimal grossTotal, BigDecimal excessPercentage, BigDecimal excessRate, BigDecimal educationCessPercentage, BigDecimal educationCessRate, BigDecimal secondaryEducationCessPercentage, BigDecimal secondaryEducationCessRate, BigDecimal cstpercentage, BigDecimal cstrate, BigDecimal vattotal1, BigDecimal vattotal2, BigDecimal roundOff, BigDecimal totalAmount, Date enteredDate, Set imsPurchaseproductdetailses, Set imsPurchaseproductdetailses_1) {
       this.pinvoiceId = pinvoiceId;
       this.imsSuppliermaster = imsSuppliermaster;
       this.imsLogindetails = imsLogindetails;
       this.cashorCredit = cashorCredit;
       this.supplierOrderNo = supplierOrderNo;
       this.repName = repName;
       this.supplierInvoiceDate = supplierInvoiceDate;
       this.paymentDueDate = paymentDueDate;
       this.paymentTerms = paymentTerms;
       this.frieghtTerm = frieghtTerm;
       this.deliverlyTerm = deliverlyTerm;
       this.transporter = transporter;
       this.transportMode = transportMode;
       this.esugamaNo = esugamaNo;
       this.destination = destination;
       this.lrnoandDate = lrnoandDate;
       this.expectedDelivary = expectedDelivary;
       this.noPacks = noPacks;
       this.grossWeight = grossWeight;
       this.totalNoproducts = totalNoproducts;
       this.vatfaf = vatfaf;
       this.vatfafrate = vatfafrate;
       this.grossTotal = grossTotal;
       this.excessPercentage = excessPercentage;
       this.excessRate = excessRate;
       this.educationCessPercentage = educationCessPercentage;
       this.educationCessRate = educationCessRate;
       this.secondaryEducationCessPercentage = secondaryEducationCessPercentage;
       this.secondaryEducationCessRate = secondaryEducationCessRate;
       this.cstpercentage = cstpercentage;
       this.cstrate = cstrate;
       this.vattotal1 = vattotal1;
       this.vattotal2 = vattotal2;
       this.roundOff = roundOff;
       this.totalAmount = totalAmount;
       this.enteredDate = enteredDate;
       this.imsPurchaseproductdetailses = imsPurchaseproductdetailses;
       this.imsPurchaseproductdetailses_1 = imsPurchaseproductdetailses_1;
    }
   
    public String getPinvoiceId() {
        return this.pinvoiceId;
    }
    
    public void setPinvoiceId(String pinvoiceId) {
        this.pinvoiceId = pinvoiceId;
    }
    public ImsSuppliermaster getImsSuppliermaster() {
        return this.imsSuppliermaster;
    }
    
    public void setImsSuppliermaster(ImsSuppliermaster imsSuppliermaster) {
        this.imsSuppliermaster = imsSuppliermaster;
    }
    public ImsLogindetails getImsLogindetails() {
        return this.imsLogindetails;
    }
    
    public void setImsLogindetails(ImsLogindetails imsLogindetails) {
        this.imsLogindetails = imsLogindetails;
    }
    public String getCashorCredit() {
        return this.cashorCredit;
    }
    
    public void setCashorCredit(String cashorCredit) {
        this.cashorCredit = cashorCredit;
    }
    public String getSupplierOrderNo() {
        return this.supplierOrderNo;
    }
    
    public void setSupplierOrderNo(String supplierOrderNo) {
        this.supplierOrderNo = supplierOrderNo;
    }
    public String getRepName() {
        return this.repName;
    }
    
    public void setRepName(String repName) {
        this.repName = repName;
    }
    public Date getSupplierInvoiceDate() {
        return this.supplierInvoiceDate;
    }
    
    public void setSupplierInvoiceDate(Date supplierInvoiceDate) {
        this.supplierInvoiceDate = supplierInvoiceDate;
    }
    public Date getPaymentDueDate() {
        return this.paymentDueDate;
    }
    
    public void setPaymentDueDate(Date paymentDueDate) {
        this.paymentDueDate = paymentDueDate;
    }
    public String getPaymentTerms() {
        return this.paymentTerms;
    }
    
    public void setPaymentTerms(String paymentTerms) {
        this.paymentTerms = paymentTerms;
    }
    public String getFrieghtTerm() {
        return this.frieghtTerm;
    }
    
    public void setFrieghtTerm(String frieghtTerm) {
        this.frieghtTerm = frieghtTerm;
    }
    public String getDeliverlyTerm() {
        return this.deliverlyTerm;
    }
    
    public void setDeliverlyTerm(String deliverlyTerm) {
        this.deliverlyTerm = deliverlyTerm;
    }
    public String getTransporter() {
        return this.transporter;
    }
    
    public void setTransporter(String transporter) {
        this.transporter = transporter;
    }
    public String getTransportMode() {
        return this.transportMode;
    }
    
    public void setTransportMode(String transportMode) {
        this.transportMode = transportMode;
    }
    public String getEsugamaNo() {
        return this.esugamaNo;
    }
    
    public void setEsugamaNo(String esugamaNo) {
        this.esugamaNo = esugamaNo;
    }
    public String getDestination() {
        return this.destination;
    }
    
    public void setDestination(String destination) {
        this.destination = destination;
    }
    public String getLrnoandDate() {
        return this.lrnoandDate;
    }
    
    public void setLrnoandDate(String lrnoandDate) {
        this.lrnoandDate = lrnoandDate;
    }
    public Date getExpectedDelivary() {
        return this.expectedDelivary;
    }
    
    public void setExpectedDelivary(Date expectedDelivary) {
        this.expectedDelivary = expectedDelivary;
    }
    public Long getNoPacks() {
        return this.noPacks;
    }
    
    public void setNoPacks(Long noPacks) {
        this.noPacks = noPacks;
    }
    public BigDecimal getGrossWeight() {
        return this.grossWeight;
    }
    
    public void setGrossWeight(BigDecimal grossWeight) {
        this.grossWeight = grossWeight;
    }
    public Long getTotalNoproducts() {
        return this.totalNoproducts;
    }
    
    public void setTotalNoproducts(Long totalNoproducts) {
        this.totalNoproducts = totalNoproducts;
    }
    public BigDecimal getVatfaf() {
        return this.vatfaf;
    }
    
    public void setVatfaf(BigDecimal vatfaf) {
        this.vatfaf = vatfaf;
    }
    public BigDecimal getVatfafrate() {
        return this.vatfafrate;
    }
    
    public void setVatfafrate(BigDecimal vatfafrate) {
        this.vatfafrate = vatfafrate;
    }
    public BigDecimal getGrossTotal() {
        return this.grossTotal;
    }
    
    public void setGrossTotal(BigDecimal grossTotal) {
        this.grossTotal = grossTotal;
    }
    public BigDecimal getExcessPercentage() {
        return this.excessPercentage;
    }
    
    public void setExcessPercentage(BigDecimal excessPercentage) {
        this.excessPercentage = excessPercentage;
    }
    public BigDecimal getExcessRate() {
        return this.excessRate;
    }
    
    public void setExcessRate(BigDecimal excessRate) {
        this.excessRate = excessRate;
    }
    public BigDecimal getEducationCessPercentage() {
        return this.educationCessPercentage;
    }
    
    public void setEducationCessPercentage(BigDecimal educationCessPercentage) {
        this.educationCessPercentage = educationCessPercentage;
    }
    public BigDecimal getEducationCessRate() {
        return this.educationCessRate;
    }
    
    public void setEducationCessRate(BigDecimal educationCessRate) {
        this.educationCessRate = educationCessRate;
    }
    public BigDecimal getSecondaryEducationCessPercentage() {
        return this.secondaryEducationCessPercentage;
    }
    
    public void setSecondaryEducationCessPercentage(BigDecimal secondaryEducationCessPercentage) {
        this.secondaryEducationCessPercentage = secondaryEducationCessPercentage;
    }
    public BigDecimal getSecondaryEducationCessRate() {
        return this.secondaryEducationCessRate;
    }
    
    public void setSecondaryEducationCessRate(BigDecimal secondaryEducationCessRate) {
        this.secondaryEducationCessRate = secondaryEducationCessRate;
    }
    public BigDecimal getCstpercentage() {
        return this.cstpercentage;
    }
    
    public void setCstpercentage(BigDecimal cstpercentage) {
        this.cstpercentage = cstpercentage;
    }
    public BigDecimal getCstrate() {
        return this.cstrate;
    }
    
    public void setCstrate(BigDecimal cstrate) {
        this.cstrate = cstrate;
    }
    public BigDecimal getVattotal1() {
        return this.vattotal1;
    }
    
    public void setVattotal1(BigDecimal vattotal1) {
        this.vattotal1 = vattotal1;
    }
    public BigDecimal getVattotal2() {
        return this.vattotal2;
    }
    
    public void setVattotal2(BigDecimal vattotal2) {
        this.vattotal2 = vattotal2;
    }
    public BigDecimal getRoundOff() {
        return this.roundOff;
    }
    
    public void setRoundOff(BigDecimal roundOff) {
        this.roundOff = roundOff;
    }
    public BigDecimal getTotalAmount() {
        return this.totalAmount;
    }
    
    public void setTotalAmount(BigDecimal totalAmount) {
        this.totalAmount = totalAmount;
    }
    public Date getEnteredDate() {
        return this.enteredDate;
    }
    
    public void setEnteredDate(Date enteredDate) {
        this.enteredDate = enteredDate;
    }
    public Set getImsPurchaseproductdetailses() {
        return this.imsPurchaseproductdetailses;
    }
    
    public void setImsPurchaseproductdetailses(Set imsPurchaseproductdetailses) {
        this.imsPurchaseproductdetailses = imsPurchaseproductdetailses;
    }
    public Set getImsPurchaseproductdetailses_1() {
        return this.imsPurchaseproductdetailses_1;
    }
    
    public void setImsPurchaseproductdetailses_1(Set imsPurchaseproductdetailses_1) {
        this.imsPurchaseproductdetailses_1 = imsPurchaseproductdetailses_1;
    }




}


