package org.ims.dao.entity;
// Generated 25 Jan, 2016 10:53:23 PM by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * ImsProductdetails generated by hbm2java
 */
public class ImsProductdetails  implements java.io.Serializable {


     private String productCode;
     private ImsProductcategory imsProductcategory;
     private ImsLogindetails imsLogindetails;
     private String productName;
     private String specificationAndThickNess;
     private String units;
     private String size;
     private Long moq;
     private String color;
     private Date enteredDate;
     private Set imsSalesproductdetailses = new HashSet(0);
     private Set imsSalesproductdetailses_1 = new HashSet(0);
     private Set imsOrderdetailses = new HashSet(0);
     private ImsStockdetails imsStockdetails;
     private Set imsPurchaseproductdetailses = new HashSet(0);
     private Set imsPurchaseproductdetailses_1 = new HashSet(0);
     private Set imsOrderdetailses_1 = new HashSet(0);

    public ImsProductdetails() {
    }

	
    public ImsProductdetails(String productCode) {
        this.productCode = productCode;
    }
    public ImsProductdetails(String productCode, ImsProductcategory imsProductcategory, ImsLogindetails imsLogindetails, String productName, String specificationAndThickNess, String units, String size, Long moq, String color, Date enteredDate, Set imsSalesproductdetailses, Set imsSalesproductdetailses_1, Set imsOrderdetailses, ImsStockdetails imsStockdetails, Set imsPurchaseproductdetailses, Set imsPurchaseproductdetailses_1, Set imsOrderdetailses_1) {
       this.productCode = productCode;
       this.imsProductcategory = imsProductcategory;
       this.imsLogindetails = imsLogindetails;
       this.productName = productName;
       this.specificationAndThickNess = specificationAndThickNess;
       this.units = units;
       this.size = size;
       this.moq = moq;
       this.color = color;
       this.enteredDate = enteredDate;
       this.imsSalesproductdetailses = imsSalesproductdetailses;
       this.imsSalesproductdetailses_1 = imsSalesproductdetailses_1;
       this.imsOrderdetailses = imsOrderdetailses;
       this.imsStockdetails = imsStockdetails;
       this.imsPurchaseproductdetailses = imsPurchaseproductdetailses;
       this.imsPurchaseproductdetailses_1 = imsPurchaseproductdetailses_1;
       this.imsOrderdetailses_1 = imsOrderdetailses_1;
    }
   
    public String getProductCode() {
        return this.productCode;
    }
    
    public void setProductCode(String productCode) {
        this.productCode = productCode;
    }
    public ImsProductcategory getImsProductcategory() {
        return this.imsProductcategory;
    }
    
    public void setImsProductcategory(ImsProductcategory imsProductcategory) {
        this.imsProductcategory = imsProductcategory;
    }
    public ImsLogindetails getImsLogindetails() {
        return this.imsLogindetails;
    }
    
    public void setImsLogindetails(ImsLogindetails imsLogindetails) {
        this.imsLogindetails = imsLogindetails;
    }
    public String getProductName() {
        return this.productName;
    }
    
    public void setProductName(String productName) {
        this.productName = productName;
    }
    public String getSpecificationAndThickNess() {
        return this.specificationAndThickNess;
    }
    
    public void setSpecificationAndThickNess(String specificationAndThickNess) {
        this.specificationAndThickNess = specificationAndThickNess;
    }
    public String getUnits() {
        return this.units;
    }
    
    public void setUnits(String units) {
        this.units = units;
    }
    public String getSize() {
        return this.size;
    }
    
    public void setSize(String size) {
        this.size = size;
    }
    public Long getMoq() {
        return this.moq;
    }
    
    public void setMoq(Long moq) {
        this.moq = moq;
    }
    public String getColor() {
        return this.color;
    }
    
    public void setColor(String color) {
        this.color = color;
    }
    public Date getEnteredDate() {
        return this.enteredDate;
    }
    
    public void setEnteredDate(Date enteredDate) {
        this.enteredDate = enteredDate;
    }
    public Set getImsSalesproductdetailses() {
        return this.imsSalesproductdetailses;
    }
    
    public void setImsSalesproductdetailses(Set imsSalesproductdetailses) {
        this.imsSalesproductdetailses = imsSalesproductdetailses;
    }
    public Set getImsSalesproductdetailses_1() {
        return this.imsSalesproductdetailses_1;
    }
    
    public void setImsSalesproductdetailses_1(Set imsSalesproductdetailses_1) {
        this.imsSalesproductdetailses_1 = imsSalesproductdetailses_1;
    }
    public Set getImsOrderdetailses() {
        return this.imsOrderdetailses;
    }
    
    public void setImsOrderdetailses(Set imsOrderdetailses) {
        this.imsOrderdetailses = imsOrderdetailses;
    }
    public ImsStockdetails getImsStockdetails() {
        return this.imsStockdetails;
    }
    
    public void setImsStockdetails(ImsStockdetails imsStockdetails) {
        this.imsStockdetails = imsStockdetails;
    }
    public Set getImsPurchaseproductdetailses() {
        return this.imsPurchaseproductdetailses;
    }
    
    public void setImsPurchaseproductdetailses(Set imsPurchaseproductdetailses) {
        this.imsPurchaseproductdetailses = imsPurchaseproductdetailses;
    }
    public Set getImsPurchaseproductdetailses_1() {
        return this.imsPurchaseproductdetailses_1;
    }
    
    public void setImsPurchaseproductdetailses_1(Set imsPurchaseproductdetailses_1) {
        this.imsPurchaseproductdetailses_1 = imsPurchaseproductdetailses_1;
    }
    public Set getImsOrderdetailses_1() {
        return this.imsOrderdetailses_1;
    }
    
    public void setImsOrderdetailses_1(Set imsOrderdetailses_1) {
        this.imsOrderdetailses_1 = imsOrderdetailses_1;
    }




}


