package org.ims.dao.entity;
// Generated Nov 17, 2016 12:01:36 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * ImsProductcategory generated by hbm2java
 */
public class ImsProductcategory  implements java.io.Serializable {


     private String categoryCode;
     private ImsLogindetails imsLogindetails;
     private String categoryName;
     private String additionalInfo;
     private Date enteredDate;
     private Set imsProductdetailses = new HashSet(0);

    public ImsProductcategory() {
    }

	
    public ImsProductcategory(String categoryCode, ImsLogindetails imsLogindetails) {
        this.categoryCode = categoryCode;
        this.imsLogindetails = imsLogindetails;
    }
    public ImsProductcategory(String categoryCode, ImsLogindetails imsLogindetails, String categoryName, String additionalInfo, Date enteredDate, Set imsProductdetailses) {
       this.categoryCode = categoryCode;
       this.imsLogindetails = imsLogindetails;
       this.categoryName = categoryName;
       this.additionalInfo = additionalInfo;
       this.enteredDate = enteredDate;
       this.imsProductdetailses = imsProductdetailses;
    }
   
    public String getCategoryCode() {
        return this.categoryCode;
    }
    
    public void setCategoryCode(String categoryCode) {
        this.categoryCode = categoryCode;
    }
    public ImsLogindetails getImsLogindetails() {
        return this.imsLogindetails;
    }
    
    public void setImsLogindetails(ImsLogindetails imsLogindetails) {
        this.imsLogindetails = imsLogindetails;
    }
    public String getCategoryName() {
        return this.categoryName;
    }
    
    public void setCategoryName(String categoryName) {
        this.categoryName = categoryName;
    }
    public String getAdditionalInfo() {
        return this.additionalInfo;
    }
    
    public void setAdditionalInfo(String additionalInfo) {
        this.additionalInfo = additionalInfo;
    }
    public Date getEnteredDate() {
        return this.enteredDate;
    }
    
    public void setEnteredDate(Date enteredDate) {
        this.enteredDate = enteredDate;
    }
    public Set getImsProductdetailses() {
        return this.imsProductdetailses;
    }
    
    public void setImsProductdetailses(Set imsProductdetailses) {
        this.imsProductdetailses = imsProductdetailses;
    }




}


