package org.ims.dao.entity;
// Generated Dec 27, 2016 11:33:32 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * ImsSalesproductdetails generated by hbm2java
 */
public class ImsSalesproductdetails  implements java.io.Serializable {


     private ImsSalesproductdetailsId id;
     private ImsProductdetails imsProductdetails;
     private ImsSalesmaster imsSalesmaster;
     private String particulars;
     private Integer orderQty;
     private Integer dispatchedQty;
     private Integer balanceQty;
     private String discount;
     private Double salesPrie;
     private Long enteredBy;
     private Date enteredDate;

    public ImsSalesproductdetails() {
    }

	
    public ImsSalesproductdetails(ImsSalesproductdetailsId id, ImsSalesmaster imsSalesmaster) {
        this.id = id;
        this.imsSalesmaster = imsSalesmaster;
    }
    public ImsSalesproductdetails(ImsSalesproductdetailsId id, ImsProductdetails imsProductdetails, ImsSalesmaster imsSalesmaster, String particulars, Integer orderQty, Integer dispatchedQty, Integer balanceQty, String discount, Double salesPrie, Long enteredBy, Date enteredDate) {
       this.id = id;
       this.imsProductdetails = imsProductdetails;
       this.imsSalesmaster = imsSalesmaster;
       this.particulars = particulars;
       this.orderQty = orderQty;
       this.dispatchedQty = dispatchedQty;
       this.balanceQty = balanceQty;
       this.discount = discount;
       this.salesPrie = salesPrie;
       this.enteredBy = enteredBy;
       this.enteredDate = enteredDate;
    }
   
    public ImsSalesproductdetailsId getId() {
        return this.id;
    }
    
    public void setId(ImsSalesproductdetailsId id) {
        this.id = id;
    }
    public ImsProductdetails getImsProductdetails() {
        return this.imsProductdetails;
    }
    
    public void setImsProductdetails(ImsProductdetails imsProductdetails) {
        this.imsProductdetails = imsProductdetails;
    }
    public ImsSalesmaster getImsSalesmaster() {
        return this.imsSalesmaster;
    }
    
    public void setImsSalesmaster(ImsSalesmaster imsSalesmaster) {
        this.imsSalesmaster = imsSalesmaster;
    }
    public String getParticulars() {
        return this.particulars;
    }
    
    public void setParticulars(String particulars) {
        this.particulars = particulars;
    }
    public Integer getOrderQty() {
        return this.orderQty;
    }
    
    public void setOrderQty(Integer orderQty) {
        this.orderQty = orderQty;
    }
    public Integer getDispatchedQty() {
        return this.dispatchedQty;
    }
    
    public void setDispatchedQty(Integer dispatchedQty) {
        this.dispatchedQty = dispatchedQty;
    }
    public Integer getBalanceQty() {
        return this.balanceQty;
    }
    
    public void setBalanceQty(Integer balanceQty) {
        this.balanceQty = balanceQty;
    }
    public String getDiscount() {
        return this.discount;
    }
    
    public void setDiscount(String discount) {
        this.discount = discount;
    }
    public Double getSalesPrie() {
        return this.salesPrie;
    }
    
    public void setSalesPrie(Double salesPrie) {
        this.salesPrie = salesPrie;
    }
    public Long getEnteredBy() {
        return this.enteredBy;
    }
    
    public void setEnteredBy(Long enteredBy) {
        this.enteredBy = enteredBy;
    }
    public Date getEnteredDate() {
        return this.enteredDate;
    }
    
    public void setEnteredDate(Date enteredDate) {
        this.enteredDate = enteredDate;
    }




}


