package org.ims.dao.entity;
// Generated Nov 13, 2016 9:33:11 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * ImsSalesproductdetailsId generated by hbm2java
 */
public class ImsSalesproductdetailsId  implements java.io.Serializable {


     private BigDecimal transactionId;
     private String invoiceNo;

    public ImsSalesproductdetailsId() {
    }

    public ImsSalesproductdetailsId(BigDecimal transactionId, String invoiceNo) {
       this.transactionId = transactionId;
       this.invoiceNo = invoiceNo;
    }
   
    public BigDecimal getTransactionId() {
        return this.transactionId;
    }
    
    public void setTransactionId(BigDecimal transactionId) {
        this.transactionId = transactionId;
    }
    public String getInvoiceNo() {
        return this.invoiceNo;
    }
    
    public void setInvoiceNo(String invoiceNo) {
        this.invoiceNo = invoiceNo;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ImsSalesproductdetailsId) ) return false;
		 ImsSalesproductdetailsId castOther = ( ImsSalesproductdetailsId ) other; 
         
		 return ( (this.getTransactionId()==castOther.getTransactionId()) || ( this.getTransactionId()!=null && castOther.getTransactionId()!=null && this.getTransactionId().equals(castOther.getTransactionId()) ) )
 && ( (this.getInvoiceNo()==castOther.getInvoiceNo()) || ( this.getInvoiceNo()!=null && castOther.getInvoiceNo()!=null && this.getInvoiceNo().equals(castOther.getInvoiceNo()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getTransactionId() == null ? 0 : this.getTransactionId().hashCode() );
         result = 37 * result + ( getInvoiceNo() == null ? 0 : this.getInvoiceNo().hashCode() );
         return result;
   }   


}


