package org.ims.dao.entity;
// Generated Dec 27, 2016 11:33:32 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * ImsStockdetails generated by hbm2java
 */
public class ImsStockdetails  implements java.io.Serializable {


     private Long id;
     private ImsLogindetails imsLogindetails;
     private ImsProductdetails imsProductdetails;
     private Long purchasedQty;
     private Long dispatchedQty;
     private Long availableQty;
     private BigDecimal unitPrice;
     private BigDecimal totalPrice;
     private BigDecimal ourMarginPercentage;
     private BigDecimal ourMerginAmount;
     private BigDecimal dealerPrice;
     private Date enteredDate;

    public ImsStockdetails() {
    }

	
    public ImsStockdetails(ImsProductdetails imsProductdetails) {
        this.imsProductdetails = imsProductdetails;
    }
    public ImsStockdetails(ImsLogindetails imsLogindetails, ImsProductdetails imsProductdetails, Long purchasedQty, Long dispatchedQty, Long availableQty, BigDecimal unitPrice, BigDecimal totalPrice, BigDecimal ourMarginPercentage, BigDecimal ourMerginAmount, BigDecimal dealerPrice, Date enteredDate) {
       this.imsLogindetails = imsLogindetails;
       this.imsProductdetails = imsProductdetails;
       this.purchasedQty = purchasedQty;
       this.dispatchedQty = dispatchedQty;
       this.availableQty = availableQty;
       this.unitPrice = unitPrice;
       this.totalPrice = totalPrice;
       this.ourMarginPercentage = ourMarginPercentage;
       this.ourMerginAmount = ourMerginAmount;
       this.dealerPrice = dealerPrice;
       this.enteredDate = enteredDate;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public ImsLogindetails getImsLogindetails() {
        return this.imsLogindetails;
    }
    
    public void setImsLogindetails(ImsLogindetails imsLogindetails) {
        this.imsLogindetails = imsLogindetails;
    }
    public ImsProductdetails getImsProductdetails() {
        return this.imsProductdetails;
    }
    
    public void setImsProductdetails(ImsProductdetails imsProductdetails) {
        this.imsProductdetails = imsProductdetails;
    }
    public Long getPurchasedQty() {
        return this.purchasedQty;
    }
    
    public void setPurchasedQty(Long purchasedQty) {
        this.purchasedQty = purchasedQty;
    }
    public Long getDispatchedQty() {
        return this.dispatchedQty;
    }
    
    public void setDispatchedQty(Long dispatchedQty) {
        this.dispatchedQty = dispatchedQty;
    }
    public Long getAvailableQty() {
        return this.availableQty;
    }
    
    public void setAvailableQty(Long availableQty) {
        this.availableQty = availableQty;
    }
    public BigDecimal getUnitPrice() {
        return this.unitPrice;
    }
    
    public void setUnitPrice(BigDecimal unitPrice) {
        this.unitPrice = unitPrice;
    }
    public BigDecimal getTotalPrice() {
        return this.totalPrice;
    }
    
    public void setTotalPrice(BigDecimal totalPrice) {
        this.totalPrice = totalPrice;
    }
    public BigDecimal getOurMarginPercentage() {
        return this.ourMarginPercentage;
    }
    
    public void setOurMarginPercentage(BigDecimal ourMarginPercentage) {
        this.ourMarginPercentage = ourMarginPercentage;
    }
    public BigDecimal getOurMerginAmount() {
        return this.ourMerginAmount;
    }
    
    public void setOurMerginAmount(BigDecimal ourMerginAmount) {
        this.ourMerginAmount = ourMerginAmount;
    }
    public BigDecimal getDealerPrice() {
        return this.dealerPrice;
    }
    
    public void setDealerPrice(BigDecimal dealerPrice) {
        this.dealerPrice = dealerPrice;
    }
    public Date getEnteredDate() {
        return this.enteredDate;
    }
    
    public void setEnteredDate(Date enteredDate) {
        this.enteredDate = enteredDate;
    }




}


