package org.ims.dao.entity;
// Generated 25 Jan, 2016 10:53:23 PM by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * ImsSalesmaster generated by hbm2java
 */
public class ImsSalesmaster  implements java.io.Serializable {


     private String invoiceNo;
     private String cashOrCredit;
     private Integer orderNo;
     private String repName;
     private String invoiceDate;
     private String invoiceTime;
     private String paymentDueDate;
     private String paymentTerms;
     private String frieghtTerms;
     private String deliveryTerm;
     private String transporter;
     private String transportMode;
     private String esugmaNo;
     private String destination;
     private String lrnoAndDate;
     private String exptdDelivery;
     private String noOfPack;
     private String grossWieght;
     private Double vatfafcharges;
     private Double freightAndFwdCharges;
     private Double grossTotalAmount2;
     private Double excisePercentage;
     private Double exciseRate;
     private Double educationCessPercentage;
     private Double educCessRate;
     private Double secEducCessPercentage;
     private Double secEducCessRate;
     private Double cstpercentage;
     private Double cstrate;
     private Double vattotal1;
     private Double vattotal2;
     private Double roundOff;
     private Double totalAmount;
     private Long enteredBy;
     private Date enteredDate;
     private Set imsSalesproductdetailses = new HashSet(0);
     private Set imsSalesproductdetailses_1 = new HashSet(0);

    public ImsSalesmaster() {
    }

	
    public ImsSalesmaster(String invoiceNo) {
        this.invoiceNo = invoiceNo;
    }
    public ImsSalesmaster(String invoiceNo, String cashOrCredit, Integer orderNo, String repName, String invoiceDate, String invoiceTime, String paymentDueDate, String paymentTerms, String frieghtTerms, String deliveryTerm, String transporter, String transportMode, String esugmaNo, String destination, String lrnoAndDate, String exptdDelivery, String noOfPack, String grossWieght, Double vatfafcharges, Double freightAndFwdCharges, Double grossTotalAmount2, Double excisePercentage, Double exciseRate, Double educationCessPercentage, Double educCessRate, Double secEducCessPercentage, Double secEducCessRate, Double cstpercentage, Double cstrate, Double vattotal1, Double vattotal2, Double roundOff, Double totalAmount, Long enteredBy, Date enteredDate, Set imsSalesproductdetailses, Set imsSalesproductdetailses_1) {
       this.invoiceNo = invoiceNo;
       this.cashOrCredit = cashOrCredit;
       this.orderNo = orderNo;
       this.repName = repName;
       this.invoiceDate = invoiceDate;
       this.invoiceTime = invoiceTime;
       this.paymentDueDate = paymentDueDate;
       this.paymentTerms = paymentTerms;
       this.frieghtTerms = frieghtTerms;
       this.deliveryTerm = deliveryTerm;
       this.transporter = transporter;
       this.transportMode = transportMode;
       this.esugmaNo = esugmaNo;
       this.destination = destination;
       this.lrnoAndDate = lrnoAndDate;
       this.exptdDelivery = exptdDelivery;
       this.noOfPack = noOfPack;
       this.grossWieght = grossWieght;
       this.vatfafcharges = vatfafcharges;
       this.freightAndFwdCharges = freightAndFwdCharges;
       this.grossTotalAmount2 = grossTotalAmount2;
       this.excisePercentage = excisePercentage;
       this.exciseRate = exciseRate;
       this.educationCessPercentage = educationCessPercentage;
       this.educCessRate = educCessRate;
       this.secEducCessPercentage = secEducCessPercentage;
       this.secEducCessRate = secEducCessRate;
       this.cstpercentage = cstpercentage;
       this.cstrate = cstrate;
       this.vattotal1 = vattotal1;
       this.vattotal2 = vattotal2;
       this.roundOff = roundOff;
       this.totalAmount = totalAmount;
       this.enteredBy = enteredBy;
       this.enteredDate = enteredDate;
       this.imsSalesproductdetailses = imsSalesproductdetailses;
       this.imsSalesproductdetailses_1 = imsSalesproductdetailses_1;
    }
   
    public String getInvoiceNo() {
        return this.invoiceNo;
    }
    
    public void setInvoiceNo(String invoiceNo) {
        this.invoiceNo = invoiceNo;
    }
    public String getCashOrCredit() {
        return this.cashOrCredit;
    }
    
    public void setCashOrCredit(String cashOrCredit) {
        this.cashOrCredit = cashOrCredit;
    }
    public Integer getOrderNo() {
        return this.orderNo;
    }
    
    public void setOrderNo(Integer orderNo) {
        this.orderNo = orderNo;
    }
    public String getRepName() {
        return this.repName;
    }
    
    public void setRepName(String repName) {
        this.repName = repName;
    }
    public String getInvoiceDate() {
        return this.invoiceDate;
    }
    
    public void setInvoiceDate(String invoiceDate) {
        this.invoiceDate = invoiceDate;
    }
    public String getInvoiceTime() {
        return this.invoiceTime;
    }
    
    public void setInvoiceTime(String invoiceTime) {
        this.invoiceTime = invoiceTime;
    }
    public String getPaymentDueDate() {
        return this.paymentDueDate;
    }
    
    public void setPaymentDueDate(String paymentDueDate) {
        this.paymentDueDate = paymentDueDate;
    }
    public String getPaymentTerms() {
        return this.paymentTerms;
    }
    
    public void setPaymentTerms(String paymentTerms) {
        this.paymentTerms = paymentTerms;
    }
    public String getFrieghtTerms() {
        return this.frieghtTerms;
    }
    
    public void setFrieghtTerms(String frieghtTerms) {
        this.frieghtTerms = frieghtTerms;
    }
    public String getDeliveryTerm() {
        return this.deliveryTerm;
    }
    
    public void setDeliveryTerm(String deliveryTerm) {
        this.deliveryTerm = deliveryTerm;
    }
    public String getTransporter() {
        return this.transporter;
    }
    
    public void setTransporter(String transporter) {
        this.transporter = transporter;
    }
    public String getTransportMode() {
        return this.transportMode;
    }
    
    public void setTransportMode(String transportMode) {
        this.transportMode = transportMode;
    }
    public String getEsugmaNo() {
        return this.esugmaNo;
    }
    
    public void setEsugmaNo(String esugmaNo) {
        this.esugmaNo = esugmaNo;
    }
    public String getDestination() {
        return this.destination;
    }
    
    public void setDestination(String destination) {
        this.destination = destination;
    }
    public String getLrnoAndDate() {
        return this.lrnoAndDate;
    }
    
    public void setLrnoAndDate(String lrnoAndDate) {
        this.lrnoAndDate = lrnoAndDate;
    }
    public String getExptdDelivery() {
        return this.exptdDelivery;
    }
    
    public void setExptdDelivery(String exptdDelivery) {
        this.exptdDelivery = exptdDelivery;
    }
    public String getNoOfPack() {
        return this.noOfPack;
    }
    
    public void setNoOfPack(String noOfPack) {
        this.noOfPack = noOfPack;
    }
    public String getGrossWieght() {
        return this.grossWieght;
    }
    
    public void setGrossWieght(String grossWieght) {
        this.grossWieght = grossWieght;
    }
    public Double getVatfafcharges() {
        return this.vatfafcharges;
    }
    
    public void setVatfafcharges(Double vatfafcharges) {
        this.vatfafcharges = vatfafcharges;
    }
    public Double getFreightAndFwdCharges() {
        return this.freightAndFwdCharges;
    }
    
    public void setFreightAndFwdCharges(Double freightAndFwdCharges) {
        this.freightAndFwdCharges = freightAndFwdCharges;
    }
    public Double getGrossTotalAmount2() {
        return this.grossTotalAmount2;
    }
    
    public void setGrossTotalAmount2(Double grossTotalAmount2) {
        this.grossTotalAmount2 = grossTotalAmount2;
    }
    public Double getExcisePercentage() {
        return this.excisePercentage;
    }
    
    public void setExcisePercentage(Double excisePercentage) {
        this.excisePercentage = excisePercentage;
    }
    public Double getExciseRate() {
        return this.exciseRate;
    }
    
    public void setExciseRate(Double exciseRate) {
        this.exciseRate = exciseRate;
    }
    public Double getEducationCessPercentage() {
        return this.educationCessPercentage;
    }
    
    public void setEducationCessPercentage(Double educationCessPercentage) {
        this.educationCessPercentage = educationCessPercentage;
    }
    public Double getEducCessRate() {
        return this.educCessRate;
    }
    
    public void setEducCessRate(Double educCessRate) {
        this.educCessRate = educCessRate;
    }
    public Double getSecEducCessPercentage() {
        return this.secEducCessPercentage;
    }
    
    public void setSecEducCessPercentage(Double secEducCessPercentage) {
        this.secEducCessPercentage = secEducCessPercentage;
    }
    public Double getSecEducCessRate() {
        return this.secEducCessRate;
    }
    
    public void setSecEducCessRate(Double secEducCessRate) {
        this.secEducCessRate = secEducCessRate;
    }
    public Double getCstpercentage() {
        return this.cstpercentage;
    }
    
    public void setCstpercentage(Double cstpercentage) {
        this.cstpercentage = cstpercentage;
    }
    public Double getCstrate() {
        return this.cstrate;
    }
    
    public void setCstrate(Double cstrate) {
        this.cstrate = cstrate;
    }
    public Double getVattotal1() {
        return this.vattotal1;
    }
    
    public void setVattotal1(Double vattotal1) {
        this.vattotal1 = vattotal1;
    }
    public Double getVattotal2() {
        return this.vattotal2;
    }
    
    public void setVattotal2(Double vattotal2) {
        this.vattotal2 = vattotal2;
    }
    public Double getRoundOff() {
        return this.roundOff;
    }
    
    public void setRoundOff(Double roundOff) {
        this.roundOff = roundOff;
    }
    public Double getTotalAmount() {
        return this.totalAmount;
    }
    
    public void setTotalAmount(Double totalAmount) {
        this.totalAmount = totalAmount;
    }
    public Long getEnteredBy() {
        return this.enteredBy;
    }
    
    public void setEnteredBy(Long enteredBy) {
        this.enteredBy = enteredBy;
    }
    public Date getEnteredDate() {
        return this.enteredDate;
    }
    
    public void setEnteredDate(Date enteredDate) {
        this.enteredDate = enteredDate;
    }
    public Set getImsSalesproductdetailses() {
        return this.imsSalesproductdetailses;
    }
    
    public void setImsSalesproductdetailses(Set imsSalesproductdetailses) {
        this.imsSalesproductdetailses = imsSalesproductdetailses;
    }
    public Set getImsSalesproductdetailses_1() {
        return this.imsSalesproductdetailses_1;
    }
    
    public void setImsSalesproductdetailses_1(Set imsSalesproductdetailses_1) {
        this.imsSalesproductdetailses_1 = imsSalesproductdetailses_1;
    }




}


