package org.ims.dao.entity;
// Generated 25 Jan, 2016 10:53:23 PM by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * ImsSuppliermaster generated by hbm2java
 */
public class ImsSuppliermaster  implements java.io.Serializable {


     private String supplierNumber;
     private ImsLogindetails imsLogindetails;
     private String companyName;
     private String companywebsite;
     private String companyEmail;
     private String comapanyAddress;
     private String tinNumber;
     private String cstnumber;
     private String pannumber;
     private byte[] vccertificate;
     private String offlicePhNumber;
     private Date enteredDate;
     private Boolean status;
     private Set imsSuppliersauthorizers = new HashSet(0);
     private Set imsSuppliersauthorizers_1 = new HashSet(0);
     private Set imsPurchasemasters = new HashSet(0);
     private Set imsPurchasemasters_1 = new HashSet(0);

    public ImsSuppliermaster() {
    }

	
    public ImsSuppliermaster(String supplierNumber, ImsLogindetails imsLogindetails, String companyName, String tinNumber, String cstnumber, Date enteredDate) {
        this.supplierNumber = supplierNumber;
        this.imsLogindetails = imsLogindetails;
        this.companyName = companyName;
        this.tinNumber = tinNumber;
        this.cstnumber = cstnumber;
        this.enteredDate = enteredDate;
    }
    public ImsSuppliermaster(String supplierNumber, ImsLogindetails imsLogindetails, String companyName, String companywebsite, String companyEmail, String comapanyAddress, String tinNumber, String cstnumber, String pannumber, byte[] vccertificate, String offlicePhNumber, Date enteredDate, Boolean status, Set imsSuppliersauthorizers, Set imsSuppliersauthorizers_1, Set imsPurchasemasters, Set imsPurchasemasters_1) {
       this.supplierNumber = supplierNumber;
       this.imsLogindetails = imsLogindetails;
       this.companyName = companyName;
       this.companywebsite = companywebsite;
       this.companyEmail = companyEmail;
       this.comapanyAddress = comapanyAddress;
       this.tinNumber = tinNumber;
       this.cstnumber = cstnumber;
       this.pannumber = pannumber;
       this.vccertificate = vccertificate;
       this.offlicePhNumber = offlicePhNumber;
       this.enteredDate = enteredDate;
       this.status = status;
       this.imsSuppliersauthorizers = imsSuppliersauthorizers;
       this.imsSuppliersauthorizers_1 = imsSuppliersauthorizers_1;
       this.imsPurchasemasters = imsPurchasemasters;
       this.imsPurchasemasters_1 = imsPurchasemasters_1;
    }
   
    public String getSupplierNumber() {
        return this.supplierNumber;
    }
    
    public void setSupplierNumber(String supplierNumber) {
        this.supplierNumber = supplierNumber;
    }
    public ImsLogindetails getImsLogindetails() {
        return this.imsLogindetails;
    }
    
    public void setImsLogindetails(ImsLogindetails imsLogindetails) {
        this.imsLogindetails = imsLogindetails;
    }
    public String getCompanyName() {
        return this.companyName;
    }
    
    public void setCompanyName(String companyName) {
        this.companyName = companyName;
    }
    public String getCompanywebsite() {
        return this.companywebsite;
    }
    
    public void setCompanywebsite(String companywebsite) {
        this.companywebsite = companywebsite;
    }
    public String getCompanyEmail() {
        return this.companyEmail;
    }
    
    public void setCompanyEmail(String companyEmail) {
        this.companyEmail = companyEmail;
    }
    public String getComapanyAddress() {
        return this.comapanyAddress;
    }
    
    public void setComapanyAddress(String comapanyAddress) {
        this.comapanyAddress = comapanyAddress;
    }
    public String getTinNumber() {
        return this.tinNumber;
    }
    
    public void setTinNumber(String tinNumber) {
        this.tinNumber = tinNumber;
    }
    public String getCstnumber() {
        return this.cstnumber;
    }
    
    public void setCstnumber(String cstnumber) {
        this.cstnumber = cstnumber;
    }
    public String getPannumber() {
        return this.pannumber;
    }
    
    public void setPannumber(String pannumber) {
        this.pannumber = pannumber;
    }
    public byte[] getVccertificate() {
        return this.vccertificate;
    }
    
    public void setVccertificate(byte[] vccertificate) {
        this.vccertificate = vccertificate;
    }
    public String getOfflicePhNumber() {
        return this.offlicePhNumber;
    }
    
    public void setOfflicePhNumber(String offlicePhNumber) {
        this.offlicePhNumber = offlicePhNumber;
    }
    public Date getEnteredDate() {
        return this.enteredDate;
    }
    
    public void setEnteredDate(Date enteredDate) {
        this.enteredDate = enteredDate;
    }
    public Boolean getStatus() {
        return this.status;
    }
    
    public void setStatus(Boolean status) {
        this.status = status;
    }
    public Set getImsSuppliersauthorizers() {
        return this.imsSuppliersauthorizers;
    }
    
    public void setImsSuppliersauthorizers(Set imsSuppliersauthorizers) {
        this.imsSuppliersauthorizers = imsSuppliersauthorizers;
    }
    public Set getImsSuppliersauthorizers_1() {
        return this.imsSuppliersauthorizers_1;
    }
    
    public void setImsSuppliersauthorizers_1(Set imsSuppliersauthorizers_1) {
        this.imsSuppliersauthorizers_1 = imsSuppliersauthorizers_1;
    }
    public Set getImsPurchasemasters() {
        return this.imsPurchasemasters;
    }
    
    public void setImsPurchasemasters(Set imsPurchasemasters) {
        this.imsPurchasemasters = imsPurchasemasters;
    }
    public Set getImsPurchasemasters_1() {
        return this.imsPurchasemasters_1;
    }
    
    public void setImsPurchasemasters_1(Set imsPurchasemasters_1) {
        this.imsPurchasemasters_1 = imsPurchasemasters_1;
    }




}


