package org.ims.dao.entity;
// Generated Nov 13, 2016 9:33:11 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * ImsTransactiondetails generated by hbm2java
 */
public class ImsTransactiondetails  implements java.io.Serializable {


     private Integer transactionId;
     private ImsLogindetails imsLogindetails;
     private String invoiceNo;
     private Date transactionDate;
     private Integer transactionType;
     private Integer transactionCrdrtype;
     private String description;
     private Integer vocherNo;
     private String gl;
     private Date enteredDate;

    public ImsTransactiondetails() {
    }

    public ImsTransactiondetails(ImsLogindetails imsLogindetails, String invoiceNo, Date transactionDate, Integer transactionType, Integer transactionCrdrtype, String description, Integer vocherNo, String gl, Date enteredDate) {
       this.imsLogindetails = imsLogindetails;
       this.invoiceNo = invoiceNo;
       this.transactionDate = transactionDate;
       this.transactionType = transactionType;
       this.transactionCrdrtype = transactionCrdrtype;
       this.description = description;
       this.vocherNo = vocherNo;
       this.gl = gl;
       this.enteredDate = enteredDate;
    }
   
    public Integer getTransactionId() {
        return this.transactionId;
    }
    
    public void setTransactionId(Integer transactionId) {
        this.transactionId = transactionId;
    }
    public ImsLogindetails getImsLogindetails() {
        return this.imsLogindetails;
    }
    
    public void setImsLogindetails(ImsLogindetails imsLogindetails) {
        this.imsLogindetails = imsLogindetails;
    }
    public String getInvoiceNo() {
        return this.invoiceNo;
    }
    
    public void setInvoiceNo(String invoiceNo) {
        this.invoiceNo = invoiceNo;
    }
    public Date getTransactionDate() {
        return this.transactionDate;
    }
    
    public void setTransactionDate(Date transactionDate) {
        this.transactionDate = transactionDate;
    }
    public Integer getTransactionType() {
        return this.transactionType;
    }
    
    public void setTransactionType(Integer transactionType) {
        this.transactionType = transactionType;
    }
    public Integer getTransactionCrdrtype() {
        return this.transactionCrdrtype;
    }
    
    public void setTransactionCrdrtype(Integer transactionCrdrtype) {
        this.transactionCrdrtype = transactionCrdrtype;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public Integer getVocherNo() {
        return this.vocherNo;
    }
    
    public void setVocherNo(Integer vocherNo) {
        this.vocherNo = vocherNo;
    }
    public String getGl() {
        return this.gl;
    }
    
    public void setGl(String gl) {
        this.gl = gl;
    }
    public Date getEnteredDate() {
        return this.enteredDate;
    }
    
    public void setEnteredDate(Date enteredDate) {
        this.enteredDate = enteredDate;
    }




}


