package org.ims.dao.entity;
// Generated Dec 27, 2016 11:33:32 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * ImsTransactiondetails generated by hbm2java
 */
public class ImsTransactiondetails  implements java.io.Serializable {


     private Integer transactionId;
     private ImsInvoiceMaster imsInvoiceMaster;
     private ImsLogindetails imsLogindetails;
     private Date transactionDate;
     private Integer transactionType;
     private Integer transactionCrdrtype;
     private String description;
     private Integer vocherNo;
     private BigDecimal transactionAmount;
     private String gl;
     private String chequeNo;
     private Date chequeDate;
     private Integer chequeStatus;
     private Date enteredDate;

    public ImsTransactiondetails() {
    }

    public ImsTransactiondetails(ImsInvoiceMaster imsInvoiceMaster, ImsLogindetails imsLogindetails, Date transactionDate, Integer transactionType, Integer transactionCrdrtype, String description, Integer vocherNo, BigDecimal transactionAmount, String gl, String chequeNo, Date chequeDate, Integer chequeStatus, Date enteredDate) {
       this.imsInvoiceMaster = imsInvoiceMaster;
       this.imsLogindetails = imsLogindetails;
       this.transactionDate = transactionDate;
       this.transactionType = transactionType;
       this.transactionCrdrtype = transactionCrdrtype;
       this.description = description;
       this.vocherNo = vocherNo;
       this.transactionAmount = transactionAmount;
       this.gl = gl;
       this.chequeNo = chequeNo;
       this.chequeDate = chequeDate;
       this.chequeStatus = chequeStatus;
       this.enteredDate = enteredDate;
    }
   
    public Integer getTransactionId() {
        return this.transactionId;
    }
    
    public void setTransactionId(Integer transactionId) {
        this.transactionId = transactionId;
    }
    public ImsInvoiceMaster getImsInvoiceMaster() {
        return this.imsInvoiceMaster;
    }
    
    public void setImsInvoiceMaster(ImsInvoiceMaster imsInvoiceMaster) {
        this.imsInvoiceMaster = imsInvoiceMaster;
    }
    public ImsLogindetails getImsLogindetails() {
        return this.imsLogindetails;
    }
    
    public void setImsLogindetails(ImsLogindetails imsLogindetails) {
        this.imsLogindetails = imsLogindetails;
    }
    public Date getTransactionDate() {
        return this.transactionDate;
    }
    
    public void setTransactionDate(Date transactionDate) {
        this.transactionDate = transactionDate;
    }
    public Integer getTransactionType() {
        return this.transactionType;
    }
    
    public void setTransactionType(Integer transactionType) {
        this.transactionType = transactionType;
    }
    public Integer getTransactionCrdrtype() {
        return this.transactionCrdrtype;
    }
    
    public void setTransactionCrdrtype(Integer transactionCrdrtype) {
        this.transactionCrdrtype = transactionCrdrtype;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public Integer getVocherNo() {
        return this.vocherNo;
    }
    
    public void setVocherNo(Integer vocherNo) {
        this.vocherNo = vocherNo;
    }
    public BigDecimal getTransactionAmount() {
        return this.transactionAmount;
    }
    
    public void setTransactionAmount(BigDecimal transactionAmount) {
        this.transactionAmount = transactionAmount;
    }
    public String getGl() {
        return this.gl;
    }
    
    public void setGl(String gl) {
        this.gl = gl;
    }
    public String getChequeNo() {
        return this.chequeNo;
    }
    
    public void setChequeNo(String chequeNo) {
        this.chequeNo = chequeNo;
    }
    public Date getChequeDate() {
        return this.chequeDate;
    }
    
    public void setChequeDate(Date chequeDate) {
        this.chequeDate = chequeDate;
    }
    public Integer getChequeStatus() {
        return this.chequeStatus;
    }
    
    public void setChequeStatus(Integer chequeStatus) {
        this.chequeStatus = chequeStatus;
    }
    public Date getEnteredDate() {
        return this.enteredDate;
    }
    
    public void setEnteredDate(Date enteredDate) {
        this.enteredDate = enteredDate;
    }




}


